/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import session.Session;
/**
 *
 * @author mulya
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
lblFooterUserInfo.setText(
    "Login sebagai : " + Session.nama + " (" + Session.role + ")"
);

    btnDashboard.addActionListener(e -> {
        new Dashboard().setVisible(true);
        dispose();
    });

    btnBuatLaporan.addActionListener(e -> {
        new FormLaporan().setVisible(true);
        dispose();
    });

    btnBuatPostingan.addActionListener(e -> {
        new ForumDiskusi().setVisible(true);
        dispose();
    });

    btnArtikel.addActionListener(e -> {
        new FormArtikelEdukasi().setVisible(true);
        dispose();
    });
    pnlMenuForumDiskusi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    pnlMenuLaporanKasus.setCursor(new Cursor(Cursor.HAND_CURSOR));
    pnlMenuArtikelEdukasi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    pnlMenuKonselorOnline.setCursor(new Cursor(Cursor.HAND_CURSOR));
    
    pnlMenuForumDiskusi.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        new ForumDiskusi().setVisible(true);
        dispose();
    }
});

pnlMenuLaporanKasus.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        new FormLaporan().setVisible(true);
        dispose();
    }
});

pnlMenuArtikelEdukasi.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        new FormArtikelEdukasi().setVisible(true);
        dispose();
    }
});

pnlMenuKonselorOnline.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        new FormKonselorOnline().setVisible(true);
        dispose();
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lblSeparator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTopMenu = new javax.swing.JPanel();
        lblMenuFile = new javax.swing.JLabel();
        lblMenuPostingan = new javax.swing.JLabel();
        lblMenuLaporan = new javax.swing.JLabel();
        lblMenuArtikel = new javax.swing.JLabel();
        lblMenuAkun = new javax.swing.JLabel();
        lblMenuBantuan = new javax.swing.JLabel();
        pnlQuickAction = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnBuatPostingan = new javax.swing.JButton();
        btnBuatLaporan = new javax.swing.JButton();
        btnArtikel = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        lblNavigationTitle = new javax.swing.JLabel();
        pnlCategorySection = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboard = new javax.swing.JLabel();
        pnlMenuForumDiskusi = new javax.swing.JPanel();
        lblMenuForumDiskusi = new javax.swing.JLabel();
        pnlMenuLaporanKasus = new javax.swing.JPanel();
        lblMenuLaporanKasus = new javax.swing.JLabel();
        pnlMenuArtikelEdukasi = new javax.swing.JPanel();
        lblMenuArtikelEdukasi = new javax.swing.JLabel();
        pnlMenuKonselorOnline = new javax.swing.JPanel();
        lblMenuKonselorOnline = new javax.swing.JLabel();
        pnlKategoriKDRT = new javax.swing.JPanel();
        lblKategoriKDRT = new javax.swing.JLabel();
        pnlKategoriPelecehan = new javax.swing.JPanel();
        lblKategoriPelecehan = new javax.swing.JLabel();
        pnlKategoriKarir = new javax.swing.JPanel();
        lblKategoriKarir = new javax.swing.JLabel();
        pnlKategoriKesehatanMental = new javax.swing.JPanel();
        lblKategoriKesehatanMental = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblFooterPage = new javax.swing.JLabel();
        lblFooterSeparator = new javax.swing.JLabel();
        lblFooterUserInfo = new javax.swing.JLabel();
        pnlDashboardContent = new javax.swing.JPanel();
        pnlStatTotalPostingan = new javax.swing.JPanel();
        lblStatTotalPostinganTitle = new javax.swing.JLabel();
        lblStatTotalPostinganValue = new javax.swing.JLabel();
        pnlStatLaporanMasuk = new javax.swing.JPanel();
        lblStatLaporanMasukTitle = new javax.swing.JLabel();
        lblStatLaporanMasukValue = new javax.swing.JLabel();
        pnlStatKonselorAktif = new javax.swing.JPanel();
        lblStatKonselorAktifTitle = new javax.swing.JLabel();
        lblStatKonselorAktifValue = new javax.swing.JLabel();
        pnlStatMemberAktif = new javax.swing.JPanel();
        lblStatMemberAktifTitle = new javax.swing.JLabel();
        lblStatMemberAktifValue = new javax.swing.JLabel();
        lblPostinganTerbaru = new javax.swing.JLabel();
        pnlPostinganTerbaru = new javax.swing.JPanel();
        pnlDaftarPostingan = new javax.swing.JPanel();
        lblArtikelEdukasi = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(140, 60));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Dashboard");

        lblSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lblSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(14, 14, 14)
                .addComponent(lblSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle)
                    .addComponent(lblSeparator))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTopMenu.setBackground(new java.awt.Color(224, 205, 213));

        lblMenuFile.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuFile.setText("File");

        lblMenuPostingan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuPostingan.setText("Postingan");

        lblMenuLaporan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporan.setText("Laporan");

        lblMenuArtikel.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikel.setText("Artikel");

        lblMenuAkun.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuAkun.setText("Akun");

        lblMenuBantuan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuBantuan.setText("Bantuan");

        javax.swing.GroupLayout pnlTopMenuLayout = new javax.swing.GroupLayout(pnlTopMenu);
        pnlTopMenu.setLayout(pnlTopMenuLayout);
        pnlTopMenuLayout.setHorizontalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMenuFile)
                .addGap(44, 44, 44)
                .addComponent(lblMenuPostingan)
                .addGap(45, 45, 45)
                .addComponent(lblMenuLaporan)
                .addGap(50, 50, 50)
                .addComponent(lblMenuArtikel)
                .addGap(56, 56, 56)
                .addComponent(lblMenuAkun)
                .addGap(57, 57, 57)
                .addComponent(lblMenuBantuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopMenuLayout.setVerticalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuFile)
                    .addComponent(lblMenuPostingan)
                    .addComponent(lblMenuLaporan)
                    .addComponent(lblMenuArtikel)
                    .addComponent(lblMenuAkun)
                    .addComponent(lblMenuBantuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDashboard.setForeground(new java.awt.Color(44, 26, 34));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnBuatPostingan.setForeground(new java.awt.Color(44, 26, 34));
        btnBuatPostingan.setText("Diskusi");

        btnBuatLaporan.setForeground(new java.awt.Color(44, 26, 34));
        btnBuatLaporan.setText("Buat Laporan");
        btnBuatLaporan.addActionListener(this::btnBuatLaporanActionPerformed);

        btnArtikel.setForeground(new java.awt.Color(44, 26, 34));
        btnArtikel.setText("Artikel");

        javax.swing.GroupLayout pnlQuickActionLayout = new javax.swing.GroupLayout(pnlQuickAction);
        pnlQuickAction.setLayout(pnlQuickActionLayout);
        pnlQuickActionLayout.setHorizontalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuickActionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDashboard)
                .addGap(45, 45, 45)
                .addComponent(btnBuatPostingan)
                .addGap(52, 52, 52)
                .addComponent(btnBuatLaporan)
                .addGap(45, 45, 45)
                .addComponent(btnArtikel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlQuickActionLayout.setVerticalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuickActionLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(btnBuatPostingan)
                    .addComponent(btnBuatLaporan)
                    .addComponent(btnArtikel))
                .addContainerGap())
        );

        pnlNavigation.setBackground(new java.awt.Color(255, 255, 255));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(210, 407));

        lblNavigationTitle.setForeground(new java.awt.Color(158, 123, 135));
        lblNavigationTitle.setText("NAVIGASI");

        pnlCategorySection.setForeground(new java.awt.Color(158, 123, 135));
        pnlCategorySection.setText("KATEGORI");

        pnlMenuDashboard.setBackground(new java.awt.Color(245, 224, 229));

        lblMenuDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlMenuDashboardLayout = new javax.swing.GroupLayout(pnlMenuDashboard);
        pnlMenuDashboard.setLayout(pnlMenuDashboardLayout);
        pnlMenuDashboardLayout.setHorizontalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuDashboardLayout.setVerticalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuForumDiskusi.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuForumDiskusi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuForumDiskusi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuForumDiskusi.setText("Forum Diskusi");

        javax.swing.GroupLayout pnlMenuForumDiskusiLayout = new javax.swing.GroupLayout(pnlMenuForumDiskusi);
        pnlMenuForumDiskusi.setLayout(pnlMenuForumDiskusiLayout);
        pnlMenuForumDiskusiLayout.setHorizontalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuForumDiskusiLayout.setVerticalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuLaporanKasus.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuLaporanKasus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuLaporanKasus.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporanKasus.setText("Laporkan Kasus");

        javax.swing.GroupLayout pnlMenuLaporanKasusLayout = new javax.swing.GroupLayout(pnlMenuLaporanKasus);
        pnlMenuLaporanKasus.setLayout(pnlMenuLaporanKasusLayout);
        pnlMenuLaporanKasusLayout.setHorizontalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLaporanKasusLayout.setVerticalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuArtikelEdukasi.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuArtikelEdukasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuArtikelEdukasi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikelEdukasi.setText("Artikel  Edukasi");

        javax.swing.GroupLayout pnlMenuArtikelEdukasiLayout = new javax.swing.GroupLayout(pnlMenuArtikelEdukasi);
        pnlMenuArtikelEdukasi.setLayout(pnlMenuArtikelEdukasiLayout);
        pnlMenuArtikelEdukasiLayout.setHorizontalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuArtikelEdukasiLayout.setVerticalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuKonselorOnline.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuKonselorOnline.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuKonselorOnline.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuKonselorOnline.setText("Konselor Online");

        javax.swing.GroupLayout pnlMenuKonselorOnlineLayout = new javax.swing.GroupLayout(pnlMenuKonselorOnline);
        pnlMenuKonselorOnline.setLayout(pnlMenuKonselorOnlineLayout);
        pnlMenuKonselorOnlineLayout.setHorizontalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuKonselorOnlineLayout.setVerticalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKDRT.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKDRT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKDRT.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKDRT.setText("KDRT");

        javax.swing.GroupLayout pnlKategoriKDRTLayout = new javax.swing.GroupLayout(pnlKategoriKDRT);
        pnlKategoriKDRT.setLayout(pnlKategoriKDRTLayout);
        pnlKategoriKDRTLayout.setHorizontalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKDRT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKDRTLayout.setVerticalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKDRT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriPelecehan.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriPelecehan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriPelecehan.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriPelecehan.setText("Pelecehan");

        javax.swing.GroupLayout pnlKategoriPelecehanLayout = new javax.swing.GroupLayout(pnlKategoriPelecehan);
        pnlKategoriPelecehan.setLayout(pnlKategoriPelecehanLayout);
        pnlKategoriPelecehanLayout.setHorizontalGroup(
            pnlKategoriPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriPelecehanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriPelecehan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriPelecehanLayout.setVerticalGroup(
            pnlKategoriPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriPelecehanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriPelecehan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKarir.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKarir.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKarir.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKarir.setText("Karir");

        javax.swing.GroupLayout pnlKategoriKarirLayout = new javax.swing.GroupLayout(pnlKategoriKarir);
        pnlKategoriKarir.setLayout(pnlKategoriKarirLayout);
        pnlKategoriKarirLayout.setHorizontalGroup(
            pnlKategoriKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarirLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKarir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKarirLayout.setVerticalGroup(
            pnlKategoriKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKarir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKesehatanMental.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKesehatanMental.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKesehatanMental.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKesehatanMental.setText("Kesehatan Mental");

        javax.swing.GroupLayout pnlKategoriKesehatanMentalLayout = new javax.swing.GroupLayout(pnlKategoriKesehatanMental);
        pnlKategoriKesehatanMental.setLayout(pnlKategoriKesehatanMentalLayout);
        pnlKategoriKesehatanMentalLayout.setHorizontalGroup(
            pnlKategoriKesehatanMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKesehatanMentalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKesehatanMental)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlKategoriKesehatanMentalLayout.setVerticalGroup(
            pnlKategoriKesehatanMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKesehatanMentalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKesehatanMental)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblNavigationTitle))
                    .addComponent(pnlCategorySection))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriPelecehan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKarir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKesehatanMental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNavigationTitle)
                .addGap(7, 7, 7)
                .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCategorySection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriPelecehan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKarir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKesehatanMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        lblFooterPage.setText("Dashboard");

        lblFooterSeparator.setText("|");

        lblFooterUserInfo.setText("Login Sebagai: Mulya (Member)");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterUserInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFooterPage)
                    .addComponent(lblFooterSeparator)
                    .addComponent(lblFooterUserInfo))
                .addContainerGap())
        );

        pnlDashboardContent.setBackground(new java.awt.Color(251, 246, 240));

        pnlStatTotalPostingan.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatTotalPostingan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatTotalPostingan.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatTotalPostinganTitle.setForeground(new java.awt.Color(44, 26, 34));
        lblStatTotalPostinganTitle.setText("Total Postingan");

        lblStatTotalPostinganValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatTotalPostinganValue.setForeground(new java.awt.Color(44, 26, 34));
        lblStatTotalPostinganValue.setText("254");

        javax.swing.GroupLayout pnlStatTotalPostinganLayout = new javax.swing.GroupLayout(pnlStatTotalPostingan);
        pnlStatTotalPostingan.setLayout(pnlStatTotalPostinganLayout);
        pnlStatTotalPostinganLayout.setHorizontalGroup(
            pnlStatTotalPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatTotalPostinganLayout.createSequentialGroup()
                .addGroup(pnlStatTotalPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatTotalPostinganLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStatTotalPostinganTitle))
                    .addGroup(pnlStatTotalPostinganLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblStatTotalPostinganValue)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlStatTotalPostinganLayout.setVerticalGroup(
            pnlStatTotalPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatTotalPostinganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatTotalPostinganTitle)
                .addGap(0, 0, 0)
                .addComponent(lblStatTotalPostinganValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStatLaporanMasuk.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatLaporanMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatLaporanMasuk.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatLaporanMasukTitle.setForeground(new java.awt.Color(44, 26, 34));
        lblStatLaporanMasukTitle.setText("Laporan Masuk");

        lblStatLaporanMasukValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatLaporanMasukValue.setForeground(new java.awt.Color(44, 26, 34));
        lblStatLaporanMasukValue.setText("23");

        javax.swing.GroupLayout pnlStatLaporanMasukLayout = new javax.swing.GroupLayout(pnlStatLaporanMasuk);
        pnlStatLaporanMasuk.setLayout(pnlStatLaporanMasukLayout);
        pnlStatLaporanMasukLayout.setHorizontalGroup(
            pnlStatLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatLaporanMasukLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlStatLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatLaporanMasukTitle)
                    .addGroup(pnlStatLaporanMasukLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblStatLaporanMasukValue)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlStatLaporanMasukLayout.setVerticalGroup(
            pnlStatLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatLaporanMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatLaporanMasukTitle)
                .addGap(0, 0, 0)
                .addComponent(lblStatLaporanMasukValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStatKonselorAktif.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatKonselorAktif.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatKonselorAktif.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatKonselorAktifTitle.setForeground(new java.awt.Color(44, 26, 34));
        lblStatKonselorAktifTitle.setText("Konselor Aktif");

        lblStatKonselorAktifValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatKonselorAktifValue.setForeground(new java.awt.Color(44, 26, 34));
        lblStatKonselorAktifValue.setText("12");

        javax.swing.GroupLayout pnlStatKonselorAktifLayout = new javax.swing.GroupLayout(pnlStatKonselorAktif);
        pnlStatKonselorAktif.setLayout(pnlStatKonselorAktifLayout);
        pnlStatKonselorAktifLayout.setHorizontalGroup(
            pnlStatKonselorAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatKonselorAktifLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlStatKonselorAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatKonselorAktifTitle)
                    .addGroup(pnlStatKonselorAktifLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblStatKonselorAktifValue)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlStatKonselorAktifLayout.setVerticalGroup(
            pnlStatKonselorAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatKonselorAktifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatKonselorAktifTitle)
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblStatKonselorAktifValue))
        );

        pnlStatMemberAktif.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatMemberAktif.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatMemberAktif.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatMemberAktifTitle.setForeground(new java.awt.Color(44, 26, 34));
        lblStatMemberAktifTitle.setText("Member");

        lblStatMemberAktifValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatMemberAktifValue.setForeground(new java.awt.Color(44, 26, 34));
        lblStatMemberAktifValue.setText("567");

        javax.swing.GroupLayout pnlStatMemberAktifLayout = new javax.swing.GroupLayout(pnlStatMemberAktif);
        pnlStatMemberAktif.setLayout(pnlStatMemberAktifLayout);
        pnlStatMemberAktifLayout.setHorizontalGroup(
            pnlStatMemberAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatMemberAktifLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlStatMemberAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatMemberAktifValue)
                    .addComponent(lblStatMemberAktifTitle))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlStatMemberAktifLayout.setVerticalGroup(
            pnlStatMemberAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatMemberAktifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatMemberAktifTitle)
                .addGap(0, 0, 0)
                .addComponent(lblStatMemberAktifValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPostinganTerbaru.setForeground(new java.awt.Color(44, 26, 34));
        lblPostinganTerbaru.setText("Postingan Terbaru");

        pnlPostinganTerbaru.setBackground(new java.awt.Color(255, 255, 255));
        pnlPostinganTerbaru.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout pnlPostinganTerbaruLayout = new javax.swing.GroupLayout(pnlPostinganTerbaru);
        pnlPostinganTerbaru.setLayout(pnlPostinganTerbaruLayout);
        pnlPostinganTerbaruLayout.setHorizontalGroup(
            pnlPostinganTerbaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        pnlPostinganTerbaruLayout.setVerticalGroup(
            pnlPostinganTerbaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        pnlDaftarPostingan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDaftarPostinganLayout = new javax.swing.GroupLayout(pnlDaftarPostingan);
        pnlDaftarPostingan.setLayout(pnlDaftarPostinganLayout);
        pnlDaftarPostinganLayout.setHorizontalGroup(
            pnlDaftarPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        pnlDaftarPostinganLayout.setVerticalGroup(
            pnlDaftarPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblArtikelEdukasi.setText("Artikel Edukasi");

        javax.swing.GroupLayout pnlDashboardContentLayout = new javax.swing.GroupLayout(pnlDashboardContent);
        pnlDashboardContent.setLayout(pnlDashboardContentLayout);
        pnlDashboardContentLayout.setHorizontalGroup(
            pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPostinganTerbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDaftarPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                        .addComponent(pnlStatTotalPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatLaporanMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatKonselorAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatMemberAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPostinganTerbaru))
                    .addComponent(lblArtikelEdukasi))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlDashboardContentLayout.setVerticalGroup(
            pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatTotalPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatLaporanMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatKonselorAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatMemberAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPostinganTerbaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPostinganTerbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblArtikelEdukasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDaftarPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQuickAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDashboardContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlQuickAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDashboardContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuatLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuatLaporanActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtikel;
    private javax.swing.JButton btnBuatLaporan;
    private javax.swing.JButton btnBuatPostingan;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblArtikelEdukasi;
    private javax.swing.JLabel lblFooterPage;
    private javax.swing.JLabel lblFooterSeparator;
    private javax.swing.JLabel lblFooterUserInfo;
    private javax.swing.JLabel lblKategoriKDRT;
    private javax.swing.JLabel lblKategoriKarir;
    private javax.swing.JLabel lblKategoriKesehatanMental;
    private javax.swing.JLabel lblKategoriPelecehan;
    private javax.swing.JLabel lblMenuAkun;
    private javax.swing.JLabel lblMenuArtikel;
    private javax.swing.JLabel lblMenuArtikelEdukasi;
    private javax.swing.JLabel lblMenuBantuan;
    private javax.swing.JLabel lblMenuDashboard;
    private javax.swing.JLabel lblMenuFile;
    private javax.swing.JLabel lblMenuForumDiskusi;
    private javax.swing.JLabel lblMenuKonselorOnline;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuLaporanKasus;
    private javax.swing.JLabel lblMenuPostingan;
    private javax.swing.JLabel lblNavigationTitle;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPostinganTerbaru;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JLabel lblStatKonselorAktifTitle;
    private javax.swing.JLabel lblStatKonselorAktifValue;
    private javax.swing.JLabel lblStatLaporanMasukTitle;
    private javax.swing.JLabel lblStatLaporanMasukValue;
    private javax.swing.JLabel lblStatMemberAktifTitle;
    private javax.swing.JLabel lblStatMemberAktifValue;
    private javax.swing.JLabel lblStatTotalPostinganTitle;
    private javax.swing.JLabel lblStatTotalPostinganValue;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JLabel pnlCategorySection;
    private javax.swing.JPanel pnlDaftarPostingan;
    private javax.swing.JPanel pnlDashboardContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKategoriKDRT;
    private javax.swing.JPanel pnlKategoriKarir;
    private javax.swing.JPanel pnlKategoriKesehatanMental;
    private javax.swing.JPanel pnlKategoriPelecehan;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenuArtikelEdukasi;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuForumDiskusi;
    private javax.swing.JPanel pnlMenuKonselorOnline;
    private javax.swing.JPanel pnlMenuLaporanKasus;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlPostinganTerbaru;
    private javax.swing.JPanel pnlQuickAction;
    private javax.swing.JPanel pnlStatKonselorAktif;
    private javax.swing.JPanel pnlStatLaporanMasuk;
    private javax.swing.JPanel pnlStatMemberAktif;
    private javax.swing.JPanel pnlStatTotalPostingan;
    private javax.swing.JPanel pnlTopMenu;
    // End of variables declaration//GEN-END:variables
}
