/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nabil
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName());

    /**
     * Creates new form ForgotPasswordFrame
     */
    public ForgotPasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lbllSeparator = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblPageInfo = new javax.swing.JLabel();
        pnlBranding = new javax.swing.JPanel();
        lblHerVoice = new javax.swing.JLabel();
        lblBrandingTitle = new javax.swing.JLabel();
        sepBranding = new javax.swing.JSeparator();
        lblBrandingDescription = new javax.swing.JLabel();
        pnlForgotPasswordForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();
        lblBackToLogin = new javax.swing.JLabel();
        lblPasswordBaru = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(245, 240, 235));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Reset Password");

        lbllSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lbllSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(14, 14, 14)
                .addComponent(lbllSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle)
                    .addComponent(lbllSeparator))
                .addContainerGap())
        );

        pnlFooter.setBackground(new java.awt.Color(230, 225, 225));
        pnlFooter.setMinimumSize(new java.awt.Dimension(0, 30));

        lblPageInfo.setText("Halaman Forgot Password");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPageInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblPageInfo)
                .addContainerGap())
        );

        pnlBranding.setBackground(new java.awt.Color(119, 47, 80));
        pnlBranding.setPreferredSize(new java.awt.Dimension(250, 400));

        lblHerVoice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHerVoice.setForeground(new java.awt.Color(255, 255, 255));
        lblHerVoice.setText("HerVoice");

        lblBrandingTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblBrandingTitle.setForeground(new java.awt.Color(230, 210, 215));
        lblBrandingTitle.setText(" AKSES AKUN KEMBALI");

        sepBranding.setForeground(new java.awt.Color(170, 130, 140));
        sepBranding.setPreferredSize(new java.awt.Dimension(180, 10));

        lblBrandingDescription.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblBrandingDescription.setForeground(new java.awt.Color(210, 185, 190));
        lblBrandingDescription.setText("Pulihkan akunmu dengan aman.");

        javax.swing.GroupLayout pnlBrandingLayout = new javax.swing.GroupLayout(pnlBranding);
        pnlBranding.setLayout(pnlBrandingLayout);
        pnlBrandingLayout.setHorizontalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBrandingLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblBrandingDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlBrandingLayout.createSequentialGroup()
                                    .addComponent(lblBrandingTitle)
                                    .addGap(9, 9, 9))))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblHerVoice)
                        .addGap(83, 83, 83))))
        );
        pnlBrandingLayout.setVerticalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lblHerVoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandingDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlForgotPasswordForm.setBackground(new java.awt.Color(245, 240, 235));
        pnlForgotPasswordForm.setPreferredSize(new java.awt.Dimension(250, 400));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(119, 47, 80));
        lblTitle.setText("Reset Password");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(150, 120, 130));
        lblSubtitle.setText("Masukkan email dan password baru");

        txtEmail.setText("email@contoh.com");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(90, 90, 90));
        lblEmail.setText("Alamat Email");

        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(90, 90, 90));
        lblConfirmPassword.setText("Konfirmasi Password");

        btnResetPassword.setBackground(new java.awt.Color(119, 47, 80));
        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPassword.setText("Reset Password");

        lblBackToLogin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblBackToLogin.setForeground(new java.awt.Color(150, 120, 130));
        lblBackToLogin.setText("Kembali ke Login");

        lblPasswordBaru.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPasswordBaru.setForeground(new java.awt.Color(90, 90, 90));
        lblPasswordBaru.setText("Password Baru");

        txtNewPassword.addActionListener(this::txtNewPasswordActionPerformed);

        javax.swing.GroupLayout pnlForgotPasswordFormLayout = new javax.swing.GroupLayout(pnlForgotPasswordForm);
        pnlForgotPasswordForm.setLayout(pnlForgotPasswordFormLayout);
        pnlForgotPasswordFormLayout.setHorizontalGroup(
            pnlForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                .addGroup(pnlForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordBaru, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnResetPassword))
                    .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblBackToLogin))
                    .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNewPassword)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlForgotPasswordFormLayout.setVerticalGroup(
            pnlForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForgotPasswordFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(33, 33, 33)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnResetPassword)
                .addGap(12, 12, 12)
                .addComponent(lblBackToLogin)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlForgotPasswordForm, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlForgotPasswordForm, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBranding, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblBackToLogin;
    private javax.swing.JLabel lblBrandingDescription;
    private javax.swing.JLabel lblBrandingTitle;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHerVoice;
    private javax.swing.JLabel lblPageInfo;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPasswordBaru;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbllSeparator;
    private javax.swing.JPanel pnlBranding;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlForgotPasswordForm;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JSeparator sepBranding;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
