/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nabil
 */
public class FormPengaturan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPengaturan.class.getName());

    /**
     * Creates new form FormPengaturan
     */
    public FormPengaturan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContent = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        lblCurrentPage = new javax.swing.JLabel();
        lblSeparatorFooter = new javax.swing.JLabel();
        lblLoginInfo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        pnlMenuBar = new javax.swing.JPanel();
        lblMenuFile = new javax.swing.JLabel();
        lblMenuPengguna = new javax.swing.JLabel();
        lblMenuKonten = new javax.swing.JLabel();
        lblMenuLaporan = new javax.swing.JLabel();
        lblMenuPengaturan = new javax.swing.JLabel();
        lblMenuBantuan = new javax.swing.JLabel();
        pnlAdminSidebar = new javax.swing.JPanel();
        pnlAdminPanel = new javax.swing.JPanel();
        lblAdminPanel = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlKelolaPengguna = new javax.swing.JPanel();
        lblKelolaPengguna = new javax.swing.JLabel();
        pnlLaporanMasuk = new javax.swing.JPanel();
        lblLaporanMasuk = new javax.swing.JLabel();
        pnlModerasiForum = new javax.swing.JPanel();
        lblModerasiForum = new javax.swing.JLabel();
        pnlVerifikasiKonselor = new javax.swing.JPanel();
        lblVerifikasiKonselor = new javax.swing.JLabel();
        pnlKelolaArtikel = new javax.swing.JPanel();
        lblKelolaArtikel = new javax.swing.JLabel();
        pnlPengaturan = new javax.swing.JPanel();
        lblPengaturan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnlMainContent.setBackground(new java.awt.Color(251, 246, 240));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(136, 51, 87));
        jLabel14.setText("Pengaturan Umum");

        jLabel1.setText("Nama Aplikasi");

        jTextField1.setText("HerVoice");

        jLabel2.setText("Email Notifikasi Admin");

        jTextField2.setText("admin@hervoice.id");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel3.setText("Hotline Darurat Default");

        jTextField3.setText("119 ext. 8 (SAPA 129)");

        jLabel4.setText("Mode Pendaftaran");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terbuka untuk umum" }));

        jLabel5.setText("Verifikasi Konselor");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual oleh Admin" }));

        jLabel6.setText("Preferensi Sistem");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Izinkan mode pendaftaran anonim");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Moderasi otomatis kata kasar pada forum");

        jCheckBox3.setText("Kirim notifikasi email untuk laporan baru");

        jButton1.setBackground(new java.awt.Color(136, 51, 87));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan Perubahan");

        jButton2.setForeground(new java.awt.Color(136, 51, 87));
        jButton2.setText("Batalkan");

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMainContentLayout.createSequentialGroup()
                            .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2)
                                .addComponent(jLabel3)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jTextField1))
                            .addGap(87, 87, 87)
                            .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1))
                    .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMainContentLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lblCurrentPage.setText("Verifikasi Konselor");

        lblSeparatorFooter.setText("|");

        lblLoginInfo.setText("Login sebagai: Administrator");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparatorFooter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginInfo)
                    .addComponent(lblSeparatorFooter)
                    .addComponent(lblCurrentPage))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlMain.setBackground(new java.awt.Color(139, 61, 90));
        pnlMain.setPreferredSize(new java.awt.Dimension(700, 30));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Pengaturan Sistem");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(63, 63, 63)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlTopMenu.setBackground(new java.awt.Color(224, 205, 213));

        pnlMenuBar.setBackground(new java.awt.Color(224, 205, 213));

        lblMenuFile.setText("File");

        lblMenuPengguna.setText("Pengguna");

        lblMenuKonten.setText("Konten");

        lblMenuLaporan.setText("Laporan");

        lblMenuPengaturan.setText("Pengaturan");

        lblMenuBantuan.setText("Bantuan");

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMenuFile)
                .addGap(44, 44, 44)
                .addComponent(lblMenuPengguna)
                .addGap(45, 45, 45)
                .addComponent(lblMenuKonten)
                .addGap(50, 50, 50)
                .addComponent(lblMenuLaporan)
                .addGap(56, 56, 56)
                .addComponent(lblMenuPengaturan)
                .addGap(57, 57, 57)
                .addComponent(lblMenuBantuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuFile)
                    .addComponent(lblMenuPengguna)
                    .addComponent(lblMenuKonten)
                    .addComponent(lblMenuLaporan)
                    .addComponent(lblMenuPengaturan)
                    .addComponent(lblMenuBantuan))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTopMenuLayout = new javax.swing.GroupLayout(pnlTopMenu);
        pnlTopMenu.setLayout(pnlTopMenuLayout);
        pnlTopMenuLayout.setHorizontalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTopMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTopMenuLayout.setVerticalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
            .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTopMenuLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlAdminSidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminSidebar.setPreferredSize(new java.awt.Dimension(210, 407));

        pnlAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminPanel.setPreferredSize(new java.awt.Dimension(210, 407));

        lblAdminPanel.setForeground(new java.awt.Color(158, 123, 135));
        lblAdminPanel.setText("ADMIN PANEL");

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKelolaPengguna.setBackground(new java.awt.Color(255, 255, 255));
        pnlKelolaPengguna.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKelolaPengguna.setForeground(new java.awt.Color(44, 26, 34));
        lblKelolaPengguna.setText("Kelola Pengguna");

        javax.swing.GroupLayout pnlKelolaPenggunaLayout = new javax.swing.GroupLayout(pnlKelolaPengguna);
        pnlKelolaPengguna.setLayout(pnlKelolaPenggunaLayout);
        pnlKelolaPenggunaLayout.setHorizontalGroup(
            pnlKelolaPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaPenggunaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKelolaPengguna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKelolaPenggunaLayout.setVerticalGroup(
            pnlKelolaPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKelolaPengguna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLaporanMasuk.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaporanMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLaporanMasuk.setForeground(new java.awt.Color(44, 26, 34));
        lblLaporanMasuk.setText("Laporan Masuk");

        javax.swing.GroupLayout pnlLaporanMasukLayout = new javax.swing.GroupLayout(pnlLaporanMasuk);
        pnlLaporanMasuk.setLayout(pnlLaporanMasukLayout);
        pnlLaporanMasukLayout.setHorizontalGroup(
            pnlLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanMasukLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLaporanMasuk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLaporanMasukLayout.setVerticalGroup(
            pnlLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaporanMasuk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModerasiForum.setBackground(new java.awt.Color(255, 255, 255));
        pnlModerasiForum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblModerasiForum.setForeground(new java.awt.Color(44, 26, 34));
        lblModerasiForum.setText("Moderasi Forum");

        javax.swing.GroupLayout pnlModerasiForumLayout = new javax.swing.GroupLayout(pnlModerasiForum);
        pnlModerasiForum.setLayout(pnlModerasiForumLayout);
        pnlModerasiForumLayout.setHorizontalGroup(
            pnlModerasiForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModerasiForumLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblModerasiForum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModerasiForumLayout.setVerticalGroup(
            pnlModerasiForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModerasiForumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModerasiForum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVerifikasiKonselor.setBackground(new java.awt.Color(255, 255, 255));
        pnlVerifikasiKonselor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVerifikasiKonselor.setForeground(new java.awt.Color(44, 26, 34));
        lblVerifikasiKonselor.setText("Verifikasi Konselor");

        javax.swing.GroupLayout pnlVerifikasiKonselorLayout = new javax.swing.GroupLayout(pnlVerifikasiKonselor);
        pnlVerifikasiKonselor.setLayout(pnlVerifikasiKonselorLayout);
        pnlVerifikasiKonselorLayout.setHorizontalGroup(
            pnlVerifikasiKonselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifikasiKonselorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblVerifikasiKonselor)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlVerifikasiKonselorLayout.setVerticalGroup(
            pnlVerifikasiKonselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifikasiKonselorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVerifikasiKonselor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKelolaArtikel.setBackground(new java.awt.Color(255, 255, 255));
        pnlKelolaArtikel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKelolaArtikel.setForeground(new java.awt.Color(44, 26, 34));
        lblKelolaArtikel.setText("Kelola Artikel");

        javax.swing.GroupLayout pnlKelolaArtikelLayout = new javax.swing.GroupLayout(pnlKelolaArtikel);
        pnlKelolaArtikel.setLayout(pnlKelolaArtikelLayout);
        pnlKelolaArtikelLayout.setHorizontalGroup(
            pnlKelolaArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaArtikelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKelolaArtikel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKelolaArtikelLayout.setVerticalGroup(
            pnlKelolaArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaArtikelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKelolaArtikel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPengaturan.setBackground(new java.awt.Color(245, 224, 229));
        pnlPengaturan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPengaturan.setForeground(new java.awt.Color(44, 26, 34));
        lblPengaturan.setText("Pengaturan");

        javax.swing.GroupLayout pnlPengaturanLayout = new javax.swing.GroupLayout(pnlPengaturan);
        pnlPengaturan.setLayout(pnlPengaturanLayout);
        pnlPengaturanLayout.setHorizontalGroup(
            pnlPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengaturanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblPengaturan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPengaturanLayout.setVerticalGroup(
            pnlPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengaturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPengaturan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminPanelLayout = new javax.swing.GroupLayout(pnlAdminPanel);
        pnlAdminPanel.setLayout(pnlAdminPanelLayout);
        pnlAdminPanelLayout.setHorizontalGroup(
            pnlAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAdminPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKelolaPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLaporanMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlModerasiForum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlVerifikasiKonselor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKelolaArtikel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdminPanelLayout.setVerticalGroup(
            pnlAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblAdminPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKelolaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlModerasiForum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlVerifikasiKonselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKelolaArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminSidebarLayout = new javax.swing.GroupLayout(pnlAdminSidebar);
        pnlAdminSidebar.setLayout(pnlAdminSidebarLayout);
        pnlAdminSidebarLayout.setHorizontalGroup(
            pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAdminSidebarLayout.createSequentialGroup()
                    .addComponent(pnlAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        pnlAdminSidebarLayout.setVerticalGroup(
            pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAdminSidebarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addComponent(pnlTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAdminSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAdminSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPengaturan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblCurrentPage;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblKelolaArtikel;
    private javax.swing.JLabel lblKelolaPengguna;
    private javax.swing.JLabel lblLaporanMasuk;
    private javax.swing.JLabel lblLoginInfo;
    private javax.swing.JLabel lblMenuBantuan;
    private javax.swing.JLabel lblMenuFile;
    private javax.swing.JLabel lblMenuKonten;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuPengaturan;
    private javax.swing.JLabel lblMenuPengguna;
    private javax.swing.JLabel lblModerasiForum;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPengaturan;
    private javax.swing.JLabel lblSeparatorFooter;
    private javax.swing.JLabel lblVerifikasiKonselor;
    private javax.swing.JPanel pnlAdminPanel;
    private javax.swing.JPanel pnlAdminSidebar;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKelolaArtikel;
    private javax.swing.JPanel pnlKelolaPengguna;
    private javax.swing.JPanel pnlLaporanMasuk;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlModerasiForum;
    private javax.swing.JPanel pnlPengaturan;
    private javax.swing.JPanel pnlTopMenu;
    private javax.swing.JPanel pnlVerifikasiKonselor;
    // End of variables declaration//GEN-END:variables
}
