/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nabil
 */
public class FormKonselorOnline extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKonselorOnline.class.getName());

    /**
     * Creates new form FormKonselorOnline
     */
    public FormKonselorOnline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lblSeparator = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        lblMenuFile = new javax.swing.JLabel();
        lblMenuPostingan = new javax.swing.JLabel();
        lblMenuLaporan = new javax.swing.JLabel();
        lblMenuArtikel = new javax.swing.JLabel();
        lblMenuAkun = new javax.swing.JLabel();
        lblMenuBantuan = new javax.swing.JLabel();
        pnlQuickAction = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        lblNavigationTitle = new javax.swing.JLabel();
        pnlCategorySection = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboard = new javax.swing.JLabel();
        pnlMenuForumDiskusi = new javax.swing.JPanel();
        lblMenuForumDiskusi = new javax.swing.JLabel();
        pnlMenuLaporanKasus = new javax.swing.JPanel();
        lblMenuLaporanKasus = new javax.swing.JLabel();
        pnlMenuArtikelEdukasi = new javax.swing.JPanel();
        lblMenuArtikelEdukasi = new javax.swing.JLabel();
        pnlMenuKonselorOnline = new javax.swing.JPanel();
        lblMenuKonselorOnline = new javax.swing.JLabel();
        pnlKategoriKDRT = new javax.swing.JPanel();
        lblKategoriKDRT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlKategoriKDRT1 = new javax.swing.JPanel();
        lblKategoriKDRT1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlKategoriKDRT2 = new javax.swing.JPanel();
        lblKategoriKDRT2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblFooterPage = new javax.swing.JLabel();
        lblFooterSeparator = new javax.swing.JLabel();
        lblFooterUserInfo = new javax.swing.JLabel();
        pnlKonselorContent = new javax.swing.JPanel();
        lblJudulHalaman = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setPreferredSize(new java.awt.Dimension(730, 484));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Konselor Online");

        lblSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lblSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(14, 14, 14)
                .addComponent(lblSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle)
                    .addComponent(lblSeparator))
                .addContainerGap())
        );

        pnlTopMenu.setBackground(new java.awt.Color(224, 205, 213));

        lblMenuFile.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuFile.setText("File");

        lblMenuPostingan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuPostingan.setText("Postingan");

        lblMenuLaporan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporan.setText("Laporan");

        lblMenuArtikel.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikel.setText("Artikel");

        lblMenuAkun.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuAkun.setText("Akun");

        lblMenuBantuan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuBantuan.setText("Bantuan");

        javax.swing.GroupLayout pnlTopMenuLayout = new javax.swing.GroupLayout(pnlTopMenu);
        pnlTopMenu.setLayout(pnlTopMenuLayout);
        pnlTopMenuLayout.setHorizontalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMenuFile)
                .addGap(44, 44, 44)
                .addComponent(lblMenuPostingan)
                .addGap(45, 45, 45)
                .addComponent(lblMenuLaporan)
                .addGap(50, 50, 50)
                .addComponent(lblMenuArtikel)
                .addGap(56, 56, 56)
                .addComponent(lblMenuAkun)
                .addGap(57, 57, 57)
                .addComponent(lblMenuBantuan)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnlTopMenuLayout.setVerticalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuFile)
                    .addComponent(lblMenuPostingan)
                    .addComponent(lblMenuLaporan)
                    .addComponent(lblMenuArtikel)
                    .addComponent(lblMenuAkun)
                    .addComponent(lblMenuBantuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDashboard.setForeground(new java.awt.Color(44, 26, 34));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        javax.swing.GroupLayout pnlQuickActionLayout = new javax.swing.GroupLayout(pnlQuickAction);
        pnlQuickAction.setLayout(pnlQuickActionLayout);
        pnlQuickActionLayout.setHorizontalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuickActionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlQuickActionLayout.setVerticalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuickActionLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(btnDashboard)
                .addContainerGap())
        );

        pnlNavigation.setBackground(new java.awt.Color(255, 255, 255));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(210, 407));

        lblNavigationTitle.setForeground(new java.awt.Color(158, 123, 135));
        lblNavigationTitle.setText("NAVIGASI");

        pnlCategorySection.setForeground(new java.awt.Color(158, 123, 135));
        pnlCategorySection.setText("DAFTAR KONSELOR");

        pnlMenuDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlMenuDashboardLayout = new javax.swing.GroupLayout(pnlMenuDashboard);
        pnlMenuDashboard.setLayout(pnlMenuDashboardLayout);
        pnlMenuDashboardLayout.setHorizontalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuDashboardLayout.setVerticalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuForumDiskusi.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuForumDiskusi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuForumDiskusi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuForumDiskusi.setText("Forum Diskusi");

        javax.swing.GroupLayout pnlMenuForumDiskusiLayout = new javax.swing.GroupLayout(pnlMenuForumDiskusi);
        pnlMenuForumDiskusi.setLayout(pnlMenuForumDiskusiLayout);
        pnlMenuForumDiskusiLayout.setHorizontalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuForumDiskusiLayout.setVerticalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuLaporanKasus.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuLaporanKasus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuLaporanKasus.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporanKasus.setText("Laporan Kasus");

        javax.swing.GroupLayout pnlMenuLaporanKasusLayout = new javax.swing.GroupLayout(pnlMenuLaporanKasus);
        pnlMenuLaporanKasus.setLayout(pnlMenuLaporanKasusLayout);
        pnlMenuLaporanKasusLayout.setHorizontalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLaporanKasusLayout.setVerticalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuArtikelEdukasi.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuArtikelEdukasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuArtikelEdukasi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikelEdukasi.setText("Artikel  Edukasi");

        javax.swing.GroupLayout pnlMenuArtikelEdukasiLayout = new javax.swing.GroupLayout(pnlMenuArtikelEdukasi);
        pnlMenuArtikelEdukasi.setLayout(pnlMenuArtikelEdukasiLayout);
        pnlMenuArtikelEdukasiLayout.setHorizontalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuArtikelEdukasiLayout.setVerticalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuKonselorOnline.setBackground(new java.awt.Color(245, 224, 229));
        pnlMenuKonselorOnline.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuKonselorOnline.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuKonselorOnline.setText("Konselor Online");

        javax.swing.GroupLayout pnlMenuKonselorOnlineLayout = new javax.swing.GroupLayout(pnlMenuKonselorOnline);
        pnlMenuKonselorOnline.setLayout(pnlMenuKonselorOnlineLayout);
        pnlMenuKonselorOnlineLayout.setHorizontalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlMenuKonselorOnlineLayout.setVerticalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKDRT.setBackground(new java.awt.Color(245, 224, 229));
        pnlKategoriKDRT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKDRT.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKDRT.setText("Sari ");

        jLabel1.setForeground(new java.awt.Color(40, 167, 69));
        jLabel1.setText("● ");

        jLabel2.setForeground(new java.awt.Color(40, 167, 69));
        jLabel2.setText("Online");

        javax.swing.GroupLayout pnlKategoriKDRTLayout = new javax.swing.GroupLayout(pnlKategoriKDRT);
        pnlKategoriKDRT.setLayout(pnlKategoriKDRTLayout);
        pnlKategoriKDRTLayout.setHorizontalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKDRT)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKDRTLayout.setVerticalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategoriKDRT)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKDRT1.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKDRT1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKDRT1.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKDRT1.setText("Wati");

        jLabel5.setForeground(new java.awt.Color(40, 167, 69));
        jLabel5.setText("● ");

        jLabel6.setForeground(new java.awt.Color(40, 167, 69));
        jLabel6.setText("Online");

        javax.swing.GroupLayout pnlKategoriKDRT1Layout = new javax.swing.GroupLayout(pnlKategoriKDRT1);
        pnlKategoriKDRT1.setLayout(pnlKategoriKDRT1Layout);
        pnlKategoriKDRT1Layout.setHorizontalGroup(
            pnlKategoriKDRT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRT1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKDRT1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKDRT1Layout.setVerticalGroup(
            pnlKategoriKDRT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRT1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKategoriKDRT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategoriKDRT1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKDRT2.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKDRT2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKDRT2.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKDRT2.setText("Dewi");

        jLabel7.setForeground(new java.awt.Color(128, 128, 128));
        jLabel7.setText("● ");

        jLabel8.setForeground(new java.awt.Color(128, 128, 128));
        jLabel8.setText("Offline");

        javax.swing.GroupLayout pnlKategoriKDRT2Layout = new javax.swing.GroupLayout(pnlKategoriKDRT2);
        pnlKategoriKDRT2.setLayout(pnlKategoriKDRT2Layout);
        pnlKategoriKDRT2Layout.setHorizontalGroup(
            pnlKategoriKDRT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRT2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKDRT2)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKDRT2Layout.setVerticalGroup(
            pnlKategoriKDRT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRT2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKategoriKDRT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategoriKDRT2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlCategorySection))
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblNavigationTitle)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlKategoriKDRT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKDRT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavigationTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCategorySection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKDRT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKDRT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        lblFooterPage.setText("Konselor Sari");

        lblFooterSeparator.setText("|");

        lblFooterUserInfo.setText("Login Sebagai: Mulya (Member)");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFooterSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterUserInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFooterPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFooterSeparator)
                    .addComponent(lblFooterUserInfo))
                .addContainerGap())
        );

        pnlKonselorContent.setBackground(new java.awt.Color(255, 255, 255));

        lblJudulHalaman.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudulHalaman.setForeground(new java.awt.Color(33, 33, 33));
        lblJudulHalaman.setText("Konselor Online");

        jLabel3.setForeground(new java.awt.Color(120, 120, 120));
        jLabel3.setText("Pilih konselor dan mulai sesi konsultasi");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Chat dengan Sari");

        jLabel9.setForeground(new java.awt.Color(40, 167, 69));
        jLabel9.setText("● ");

        jLabel10.setForeground(new java.awt.Color(40, 167, 69));
        jLabel10.setText("Sedang Online");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        jPanel3.setBackground(new java.awt.Color(248, 245, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 220, 215)));
        jPanel3.setFocusCycleRoot(true);

        jLabel11.setText("Halo, ada yang bisa saya bantu hari ini?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(130, 130, 130));
        jLabel12.setText("09:01");

        jPanel4.setBackground(new java.awt.Color(122, 44, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 220, 215)));
        jPanel4.setForeground(new java.awt.Color(180, 180, 180));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("<html> Saya ingin konsultasi mengenai<br> situasi di rumah. </html>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel14.setForeground(new java.awt.Color(130, 130, 130));
        jLabel14.setText("09:02");

        jPanel5.setBackground(new java.awt.Color(248, 245, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 220, 215)));
        jPanel5.setFocusCycleRoot(true);
        jPanel5.setPreferredSize(new java.awt.Dimension(216, 38));

        jLabel15.setText("<html> Tentu, ceritakan lebih lanjut.<br> Saya siap mendengarkan. </html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel16.setForeground(new java.awt.Color(130, 130, 130));
        jLabel16.setText("09:03");

        jTextField1.setText("Ketik pesan...");

        jButton1.setText("Kirim");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(369, 369, 369)))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jLabel16)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKonselorContentLayout = new javax.swing.GroupLayout(pnlKonselorContent);
        pnlKonselorContent.setLayout(pnlKonselorContentLayout);
        pnlKonselorContentLayout.setHorizontalGroup(
            pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonselorContentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKonselorContentLayout.createSequentialGroup()
                        .addGroup(pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblJudulHalaman))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlKonselorContentLayout.createSequentialGroup()
                        .addGroup(pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        pnlKonselorContentLayout.setVerticalGroup(
            pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonselorContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulHalaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(pnlKonselorContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQuickAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKonselorContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlQuickAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlKonselorContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKonselorOnline().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblFooterPage;
    private javax.swing.JLabel lblFooterSeparator;
    private javax.swing.JLabel lblFooterUserInfo;
    private javax.swing.JLabel lblJudulHalaman;
    private javax.swing.JLabel lblKategoriKDRT;
    private javax.swing.JLabel lblKategoriKDRT1;
    private javax.swing.JLabel lblKategoriKDRT2;
    private javax.swing.JLabel lblMenuAkun;
    private javax.swing.JLabel lblMenuArtikel;
    private javax.swing.JLabel lblMenuArtikelEdukasi;
    private javax.swing.JLabel lblMenuBantuan;
    private javax.swing.JLabel lblMenuDashboard;
    private javax.swing.JLabel lblMenuFile;
    private javax.swing.JLabel lblMenuForumDiskusi;
    private javax.swing.JLabel lblMenuKonselorOnline;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuLaporanKasus;
    private javax.swing.JLabel lblMenuPostingan;
    private javax.swing.JLabel lblNavigationTitle;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JLabel pnlCategorySection;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKategoriKDRT;
    private javax.swing.JPanel pnlKategoriKDRT1;
    private javax.swing.JPanel pnlKategoriKDRT2;
    private javax.swing.JPanel pnlKonselorContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenuArtikelEdukasi;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuForumDiskusi;
    private javax.swing.JPanel pnlMenuKonselorOnline;
    private javax.swing.JPanel pnlMenuLaporanKasus;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlQuickAction;
    private javax.swing.JPanel pnlTopMenu;
    // End of variables declaration//GEN-END:variables
}
