/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nabil
 */
public class FormArtikelEdukasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormArtikelEdukasi.class.getName());

    /**
     * Creates new form FormArtikelEdukasi
     */
    public FormArtikelEdukasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lblSeparator = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        lblMenuFile = new javax.swing.JLabel();
        lblMenuPostingan = new javax.swing.JLabel();
        lblMenuLaporan = new javax.swing.JLabel();
        lblMenuArtikel = new javax.swing.JLabel();
        lblMenuAkun = new javax.swing.JLabel();
        lblMenuBantuan = new javax.swing.JLabel();
        pnlQuickAction = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        lblNavigationTitle = new javax.swing.JLabel();
        pnlCategorySection = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboard = new javax.swing.JLabel();
        pnlMenuForumDiskusi = new javax.swing.JPanel();
        lblMenuForumDiskusi = new javax.swing.JLabel();
        pnlMenuLaporanKasus = new javax.swing.JPanel();
        lblMenuLaporanKasus = new javax.swing.JLabel();
        pnlMenuArtikelEdukasi = new javax.swing.JPanel();
        lblMenuArtikelEdukasi = new javax.swing.JLabel();
        pnlMenuKonselorOnline = new javax.swing.JPanel();
        lblMenuKonselorOnline = new javax.swing.JLabel();
        pnlKategoriKDRT = new javax.swing.JPanel();
        lblKategoriKDRT = new javax.swing.JLabel();
        pnlKategoriPelecehan = new javax.swing.JPanel();
        lblKategoriPelecehan = new javax.swing.JLabel();
        pnlKategoriKarir = new javax.swing.JPanel();
        lblKategoriKarir = new javax.swing.JLabel();
        pnlKategoriKarir1 = new javax.swing.JPanel();
        lblKategoriKarir1 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblFooterPage = new javax.swing.JLabel();
        lblFooterSeparator = new javax.swing.JLabel();
        lblFooterUserInfo = new javax.swing.JLabel();
        pnlArtikelEdukasiContent = new javax.swing.JPanel();
        lblArtikelPilihan = new javax.swing.JLabel();
        pnlArtikelKDRT = new javax.swing.JPanel();
        pnlImgKDRT = new javax.swing.JPanel();
        lblKategoriKDRTcontent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlArtikelPelecehan = new javax.swing.JPanel();
        pnlImgKDRT1 = new javax.swing.JPanel();
        lblKategoriKDRTcontent1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlArtikelKarir = new javax.swing.JPanel();
        pnlImgKDRT2 = new javax.swing.JPanel();
        lblKategoriKDRTcontent2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlArtikelKesehatanMental = new javax.swing.JPanel();
        pnlImgKDRT3 = new javax.swing.JPanel();
        lblKategoriKDRTcontent3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 504));
        setResizable(false);

        pnlMain.setPreferredSize(new java.awt.Dimension(730, 484));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Artikel Edukasi");

        lblSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lblSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(14, 14, 14)
                .addComponent(lblSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle)
                    .addComponent(lblSeparator))
                .addContainerGap())
        );

        pnlTopMenu.setBackground(new java.awt.Color(224, 205, 213));

        lblMenuFile.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuFile.setText("File");

        lblMenuPostingan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuPostingan.setText("Postingan");

        lblMenuLaporan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporan.setText("Laporan");

        lblMenuArtikel.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikel.setText("Artikel");

        lblMenuAkun.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuAkun.setText("Akun");

        lblMenuBantuan.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuBantuan.setText("Bantuan");

        javax.swing.GroupLayout pnlTopMenuLayout = new javax.swing.GroupLayout(pnlTopMenu);
        pnlTopMenu.setLayout(pnlTopMenuLayout);
        pnlTopMenuLayout.setHorizontalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMenuFile)
                .addGap(44, 44, 44)
                .addComponent(lblMenuPostingan)
                .addGap(45, 45, 45)
                .addComponent(lblMenuLaporan)
                .addGap(50, 50, 50)
                .addComponent(lblMenuArtikel)
                .addGap(56, 56, 56)
                .addComponent(lblMenuAkun)
                .addGap(57, 57, 57)
                .addComponent(lblMenuBantuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopMenuLayout.setVerticalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuFile)
                    .addComponent(lblMenuPostingan)
                    .addComponent(lblMenuLaporan)
                    .addComponent(lblMenuArtikel)
                    .addComponent(lblMenuAkun)
                    .addComponent(lblMenuBantuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDashboard.setForeground(new java.awt.Color(44, 26, 34));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        jTextField1.setText("Cari artikel...");

        jButton1.setText("Cari");

        javax.swing.GroupLayout pnlQuickActionLayout = new javax.swing.GroupLayout(pnlQuickAction);
        pnlQuickAction.setLayout(pnlQuickActionLayout);
        pnlQuickActionLayout.setHorizontalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuickActionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDashboard)
                .addGap(377, 377, 377)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlQuickActionLayout.setVerticalGroup(
            pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuickActionLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pnlQuickActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlNavigation.setBackground(new java.awt.Color(255, 255, 255));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(210, 407));

        lblNavigationTitle.setForeground(new java.awt.Color(158, 123, 135));
        lblNavigationTitle.setText("NAVIGASI");

        pnlCategorySection.setForeground(new java.awt.Color(158, 123, 135));
        pnlCategorySection.setText("KATEGORI");

        pnlMenuDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlMenuDashboardLayout = new javax.swing.GroupLayout(pnlMenuDashboard);
        pnlMenuDashboard.setLayout(pnlMenuDashboardLayout);
        pnlMenuDashboardLayout.setHorizontalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuDashboardLayout.setVerticalGroup(
            pnlMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuForumDiskusi.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuForumDiskusi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuForumDiskusi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuForumDiskusi.setText("Forum Diskusi");

        javax.swing.GroupLayout pnlMenuForumDiskusiLayout = new javax.swing.GroupLayout(pnlMenuForumDiskusi);
        pnlMenuForumDiskusi.setLayout(pnlMenuForumDiskusiLayout);
        pnlMenuForumDiskusiLayout.setHorizontalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuForumDiskusiLayout.setVerticalGroup(
            pnlMenuForumDiskusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuForumDiskusiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuForumDiskusi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuLaporanKasus.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuLaporanKasus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuLaporanKasus.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuLaporanKasus.setText("Laporan Kasus");

        javax.swing.GroupLayout pnlMenuLaporanKasusLayout = new javax.swing.GroupLayout(pnlMenuLaporanKasus);
        pnlMenuLaporanKasus.setLayout(pnlMenuLaporanKasusLayout);
        pnlMenuLaporanKasusLayout.setHorizontalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLaporanKasusLayout.setVerticalGroup(
            pnlMenuLaporanKasusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLaporanKasusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuLaporanKasus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuArtikelEdukasi.setBackground(new java.awt.Color(245, 224, 229));
        pnlMenuArtikelEdukasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuArtikelEdukasi.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuArtikelEdukasi.setText("Artikel  Edukasi");

        javax.swing.GroupLayout pnlMenuArtikelEdukasiLayout = new javax.swing.GroupLayout(pnlMenuArtikelEdukasi);
        pnlMenuArtikelEdukasi.setLayout(pnlMenuArtikelEdukasiLayout);
        pnlMenuArtikelEdukasiLayout.setHorizontalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuArtikelEdukasiLayout.setVerticalGroup(
            pnlMenuArtikelEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuArtikelEdukasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuArtikelEdukasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuKonselorOnline.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuKonselorOnline.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMenuKonselorOnline.setForeground(new java.awt.Color(44, 26, 34));
        lblMenuKonselorOnline.setText("Konselor Online");

        javax.swing.GroupLayout pnlMenuKonselorOnlineLayout = new javax.swing.GroupLayout(pnlMenuKonselorOnline);
        pnlMenuKonselorOnline.setLayout(pnlMenuKonselorOnlineLayout);
        pnlMenuKonselorOnlineLayout.setHorizontalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlMenuKonselorOnlineLayout.setVerticalGroup(
            pnlMenuKonselorOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuKonselorOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuKonselorOnline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKDRT.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKDRT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKDRT.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKDRT.setText("KDRT");

        javax.swing.GroupLayout pnlKategoriKDRTLayout = new javax.swing.GroupLayout(pnlKategoriKDRT);
        pnlKategoriKDRT.setLayout(pnlKategoriKDRTLayout);
        pnlKategoriKDRTLayout.setHorizontalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKDRT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKDRTLayout.setVerticalGroup(
            pnlKategoriKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKDRTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKDRT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriPelecehan.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriPelecehan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriPelecehan.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriPelecehan.setText("Pelecehan");

        javax.swing.GroupLayout pnlKategoriPelecehanLayout = new javax.swing.GroupLayout(pnlKategoriPelecehan);
        pnlKategoriPelecehan.setLayout(pnlKategoriPelecehanLayout);
        pnlKategoriPelecehanLayout.setHorizontalGroup(
            pnlKategoriPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriPelecehanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriPelecehan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriPelecehanLayout.setVerticalGroup(
            pnlKategoriPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriPelecehanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriPelecehan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKarir.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKarir.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKarir.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKarir.setText("Karir");

        javax.swing.GroupLayout pnlKategoriKarirLayout = new javax.swing.GroupLayout(pnlKategoriKarir);
        pnlKategoriKarir.setLayout(pnlKategoriKarirLayout);
        pnlKategoriKarirLayout.setHorizontalGroup(
            pnlKategoriKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarirLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKarir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKarirLayout.setVerticalGroup(
            pnlKategoriKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKarir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKategoriKarir1.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategoriKarir1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKategoriKarir1.setForeground(new java.awt.Color(44, 26, 34));
        lblKategoriKarir1.setText("Kesehatan Mental");

        javax.swing.GroupLayout pnlKategoriKarir1Layout = new javax.swing.GroupLayout(pnlKategoriKarir1);
        pnlKategoriKarir1.setLayout(pnlKategoriKarir1Layout);
        pnlKategoriKarir1Layout.setHorizontalGroup(
            pnlKategoriKarir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarir1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKategoriKarir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKategoriKarir1Layout.setVerticalGroup(
            pnlKategoriKarir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriKarir1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKategoriKarir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriPelecehan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKarir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKategoriKarir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlCategorySection))
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblNavigationTitle)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavigationTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuForumDiskusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuLaporanKasus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuArtikelEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuKonselorOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCategorySection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKategoriKDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriPelecehan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKarir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKategoriKarir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        lblFooterPage.setText("Artikel Edukasi");

        lblFooterSeparator.setText("|");

        lblFooterUserInfo.setText("Login Sebagai: Mulya (Member)");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFooterUserInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFooterUserInfo)
                    .addComponent(lblFooterPage)
                    .addComponent(lblFooterSeparator))
                .addContainerGap())
        );

        pnlArtikelEdukasiContent.setBackground(new java.awt.Color(251, 246, 240));

        lblArtikelPilihan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArtikelPilihan.setForeground(new java.awt.Color(110, 39, 67));
        lblArtikelPilihan.setText("Artikel Pilihan Untukmu");

        pnlArtikelKDRT.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtikelKDRT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlImgKDRT.setBackground(new java.awt.Color(240, 220, 225));

        javax.swing.GroupLayout pnlImgKDRTLayout = new javax.swing.GroupLayout(pnlImgKDRT);
        pnlImgKDRT.setLayout(pnlImgKDRTLayout);
        pnlImgKDRTLayout.setHorizontalGroup(
            pnlImgKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgKDRTLayout.setVerticalGroup(
            pnlImgKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lblKategoriKDRTcontent.setBackground(new java.awt.Color(240, 220, 225));
        lblKategoriKDRTcontent.setText("KDRT");
        lblKategoriKDRTcontent.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Mengenali Tanda-Tanda KDRT");

        jLabel2.setForeground(new java.awt.Color(140, 140, 140));
        jLabel2.setText("Oleh Konselor Sari · 5 min");

        javax.swing.GroupLayout pnlArtikelKDRTLayout = new javax.swing.GroupLayout(pnlArtikelKDRT);
        pnlArtikelKDRT.setLayout(pnlArtikelKDRTLayout);
        pnlArtikelKDRTLayout.setHorizontalGroup(
            pnlArtikelKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImgKDRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlArtikelKDRTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtikelKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblKategoriKDRTcontent)
                    .addComponent(jLabel2))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        pnlArtikelKDRTLayout.setVerticalGroup(
            pnlArtikelKDRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtikelKDRTLayout.createSequentialGroup()
                .addComponent(pnlImgKDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategoriKDRTcontent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlArtikelPelecehan.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtikelPelecehan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlImgKDRT1.setBackground(new java.awt.Color(240, 220, 225));

        javax.swing.GroupLayout pnlImgKDRT1Layout = new javax.swing.GroupLayout(pnlImgKDRT1);
        pnlImgKDRT1.setLayout(pnlImgKDRT1Layout);
        pnlImgKDRT1Layout.setHorizontalGroup(
            pnlImgKDRT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgKDRT1Layout.setVerticalGroup(
            pnlImgKDRT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lblKategoriKDRTcontent1.setBackground(new java.awt.Color(240, 220, 225));
        lblKategoriKDRTcontent1.setText("Pelecehan");
        lblKategoriKDRTcontent1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Cara Menghadapi Pelecehan Verbal");

        jLabel4.setForeground(new java.awt.Color(140, 140, 140));
        jLabel4.setText("Oleh Konselor Wati · 4 min");

        javax.swing.GroupLayout pnlArtikelPelecehanLayout = new javax.swing.GroupLayout(pnlArtikelPelecehan);
        pnlArtikelPelecehan.setLayout(pnlArtikelPelecehanLayout);
        pnlArtikelPelecehanLayout.setHorizontalGroup(
            pnlArtikelPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImgKDRT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlArtikelPelecehanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtikelPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblKategoriKDRTcontent1)
                    .addComponent(jLabel4))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnlArtikelPelecehanLayout.setVerticalGroup(
            pnlArtikelPelecehanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtikelPelecehanLayout.createSequentialGroup()
                .addComponent(pnlImgKDRT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategoriKDRTcontent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlArtikelKarir.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtikelKarir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlImgKDRT2.setBackground(new java.awt.Color(240, 220, 225));

        javax.swing.GroupLayout pnlImgKDRT2Layout = new javax.swing.GroupLayout(pnlImgKDRT2);
        pnlImgKDRT2.setLayout(pnlImgKDRT2Layout);
        pnlImgKDRT2Layout.setHorizontalGroup(
            pnlImgKDRT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgKDRT2Layout.setVerticalGroup(
            pnlImgKDRT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lblKategoriKDRTcontent2.setBackground(new java.awt.Color(240, 220, 225));
        lblKategoriKDRTcontent2.setText("Karir");
        lblKategoriKDRTcontent2.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("Percaya Diri Saat Interview");

        jLabel6.setForeground(new java.awt.Color(140, 140, 140));
        jLabel6.setText("Oleh Admin · 6 min");

        javax.swing.GroupLayout pnlArtikelKarirLayout = new javax.swing.GroupLayout(pnlArtikelKarir);
        pnlArtikelKarir.setLayout(pnlArtikelKarirLayout);
        pnlArtikelKarirLayout.setHorizontalGroup(
            pnlArtikelKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImgKDRT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlArtikelKarirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtikelKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlArtikelKarirLayout.createSequentialGroup()
                        .addGroup(pnlArtikelKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKategoriKDRTcontent2)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlArtikelKarirLayout.setVerticalGroup(
            pnlArtikelKarirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtikelKarirLayout.createSequentialGroup()
                .addComponent(pnlImgKDRT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategoriKDRTcontent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlArtikelKesehatanMental.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtikelKesehatanMental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlImgKDRT3.setBackground(new java.awt.Color(240, 220, 225));

        javax.swing.GroupLayout pnlImgKDRT3Layout = new javax.swing.GroupLayout(pnlImgKDRT3);
        pnlImgKDRT3.setLayout(pnlImgKDRT3Layout);
        pnlImgKDRT3Layout.setHorizontalGroup(
            pnlImgKDRT3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgKDRT3Layout.setVerticalGroup(
            pnlImgKDRT3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lblKategoriKDRTcontent3.setBackground(new java.awt.Color(240, 220, 225));
        lblKategoriKDRTcontent3.setText("Kesehatan Mental");
        lblKategoriKDRTcontent3.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Mengelola Stres dan Kecemasan");

        jLabel8.setForeground(new java.awt.Color(140, 140, 140));
        jLabel8.setText("Oleh Konselor Dewi · 5 min");

        javax.swing.GroupLayout pnlArtikelKesehatanMentalLayout = new javax.swing.GroupLayout(pnlArtikelKesehatanMental);
        pnlArtikelKesehatanMental.setLayout(pnlArtikelKesehatanMentalLayout);
        pnlArtikelKesehatanMentalLayout.setHorizontalGroup(
            pnlArtikelKesehatanMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlImgKDRT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlArtikelKesehatanMentalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtikelKesehatanMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblKategoriKDRTcontent3)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlArtikelKesehatanMentalLayout.setVerticalGroup(
            pnlArtikelKesehatanMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtikelKesehatanMentalLayout.createSequentialGroup()
                .addComponent(pnlImgKDRT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategoriKDRTcontent3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlArtikelEdukasiContentLayout = new javax.swing.GroupLayout(pnlArtikelEdukasiContent);
        pnlArtikelEdukasiContent.setLayout(pnlArtikelEdukasiContentLayout);
        pnlArtikelEdukasiContentLayout.setHorizontalGroup(
            pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtikelEdukasiContentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArtikelPilihan)
                    .addComponent(pnlArtikelKarir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlArtikelKDRT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlArtikelKesehatanMental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlArtikelPelecehan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlArtikelEdukasiContentLayout.setVerticalGroup(
            pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtikelEdukasiContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlArtikelKesehatanMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArtikelEdukasiContentLayout.createSequentialGroup()
                        .addComponent(lblArtikelPilihan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlArtikelEdukasiContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlArtikelKDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlArtikelPelecehan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(pnlArtikelKarir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlQuickAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlArtikelEdukasiContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlQuickAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlArtikelEdukasiContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormArtikelEdukasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblArtikelPilihan;
    private javax.swing.JLabel lblFooterPage;
    private javax.swing.JLabel lblFooterSeparator;
    private javax.swing.JLabel lblFooterUserInfo;
    private javax.swing.JLabel lblKategoriKDRT;
    private javax.swing.JLabel lblKategoriKDRTcontent;
    private javax.swing.JLabel lblKategoriKDRTcontent1;
    private javax.swing.JLabel lblKategoriKDRTcontent2;
    private javax.swing.JLabel lblKategoriKDRTcontent3;
    private javax.swing.JLabel lblKategoriKarir;
    private javax.swing.JLabel lblKategoriKarir1;
    private javax.swing.JLabel lblKategoriPelecehan;
    private javax.swing.JLabel lblMenuAkun;
    private javax.swing.JLabel lblMenuArtikel;
    private javax.swing.JLabel lblMenuArtikelEdukasi;
    private javax.swing.JLabel lblMenuBantuan;
    private javax.swing.JLabel lblMenuDashboard;
    private javax.swing.JLabel lblMenuFile;
    private javax.swing.JLabel lblMenuForumDiskusi;
    private javax.swing.JLabel lblMenuKonselorOnline;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuLaporanKasus;
    private javax.swing.JLabel lblMenuPostingan;
    private javax.swing.JLabel lblNavigationTitle;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JPanel pnlArtikelEdukasiContent;
    private javax.swing.JPanel pnlArtikelKDRT;
    private javax.swing.JPanel pnlArtikelKarir;
    private javax.swing.JPanel pnlArtikelKesehatanMental;
    private javax.swing.JPanel pnlArtikelPelecehan;
    private javax.swing.JLabel pnlCategorySection;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlImgKDRT;
    private javax.swing.JPanel pnlImgKDRT1;
    private javax.swing.JPanel pnlImgKDRT2;
    private javax.swing.JPanel pnlImgKDRT3;
    private javax.swing.JPanel pnlKategoriKDRT;
    private javax.swing.JPanel pnlKategoriKarir;
    private javax.swing.JPanel pnlKategoriKarir1;
    private javax.swing.JPanel pnlKategoriPelecehan;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenuArtikelEdukasi;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuForumDiskusi;
    private javax.swing.JPanel pnlMenuKonselorOnline;
    private javax.swing.JPanel pnlMenuLaporanKasus;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlQuickAction;
    private javax.swing.JPanel pnlTopMenu;
    // End of variables declaration//GEN-END:variables
}
