/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import dao.UserDAO;
/**
 *
 * @author nabil
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
public LoginFrame() {
    initComponents();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jHerVoiceHeader = new javax.swing.JLabel();
        jDashboardHeader = new javax.swing.JLabel();
        lblNavSeparator = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblFooterInfo = new javax.swing.JLabel();
        pnlBranding = new javax.swing.JPanel();
        lblHerVoice = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        sepBranding = new javax.swing.JSeparator();
        lblDescription = new javax.swing.JLabel();
        pnlLoginForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblRegisterLink = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        btnGuest = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HerVoice_Login");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        pnlMain.setBackground(new java.awt.Color(245, 240, 235));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        jHerVoiceHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHerVoiceHeader.setText("HerVoice");

        jDashboardHeader.setForeground(new java.awt.Color(255, 255, 255));
        jDashboardHeader.setText("Masuk");

        lblNavSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lblNavSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jHerVoiceHeader)
                .addGap(14, 14, 14)
                .addComponent(lblNavSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDashboardHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHerVoiceHeader)
                    .addComponent(jDashboardHeader)
                    .addComponent(lblNavSeparator))
                .addContainerGap())
        );

        pnlFooter.setBackground(new java.awt.Color(230, 225, 225));
        pnlFooter.setMinimumSize(new java.awt.Dimension(0, 30));

        lblFooterInfo.setText("Halaman Login");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterInfo)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlBranding.setBackground(new java.awt.Color(119, 47, 80));
        pnlBranding.setPreferredSize(new java.awt.Dimension(250, 400));

        lblHerVoice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHerVoice.setForeground(new java.awt.Color(255, 255, 255));
        lblHerVoice.setText("HerVoice");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(230, 210, 215));
        lblWelcome.setText("SELAMAT DATANG KEMBALI");

        sepBranding.setForeground(new java.awt.Color(170, 130, 140));
        sepBranding.setPreferredSize(new java.awt.Dimension(180, 10));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(210, 185, 190));
        lblDescription.setText("Suara aman. Komunitas kuat. Perubahan nyata.");

        javax.swing.GroupLayout pnlBrandingLayout = new javax.swing.GroupLayout(pnlBranding);
        pnlBranding.setLayout(pnlBrandingLayout);
        pnlBrandingLayout.setHorizontalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblHerVoice)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWelcome)
                            .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        pnlBrandingLayout.setVerticalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lblHerVoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLoginForm.setBackground(new java.awt.Color(245, 240, 235));
        pnlLoginForm.setPreferredSize(new java.awt.Dimension(250, 400));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(119, 47, 80));
        lblTitle.setText("Masuk ke HerVoice ");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(150, 120, 130));
        lblSubtitle.setText("Gunakan akun yang sudah terdaftar");

        txtEmail.setText("email@contoh.com");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(90, 90, 90));
        lblEmail.setText("Alamat Email");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(90, 90, 90));
        lblPassword.setText("Password");

        btnLogin.setBackground(new java.awt.Color(119, 47, 80));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Masuk");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblRegisterLink.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegisterLink.setForeground(new java.awt.Color(150, 120, 130));
        lblRegisterLink.setText("Belum punya akun? Daftar gratis");
        lblRegisterLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterLinkMouseClicked(evt);
            }
        });

        lblForgotPassword.setForeground(new java.awt.Color(51, 51, 255));
        lblForgotPassword.setText("Lupa password? ");

        btnGuest.setBackground(new java.awt.Color(245, 240, 235));
        btnGuest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuest.setForeground(new java.awt.Color(119, 47, 80));
        btnGuest.setText("Masuk sebagai Tamu");
        btnGuest.addActionListener(this::btnGuestActionPerformed);

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout pnlLoginFormLayout = new javax.swing.GroupLayout(pnlLoginForm);
        pnlLoginForm.setLayout(pnlLoginFormLayout);
        pnlLoginFormLayout.setHorizontalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEmail))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmail))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPassword))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSubtitle))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblForgotPassword))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuest)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblRegisterLink, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPasswordField1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlLoginFormLayout.setVerticalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(33, 33, 33)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblForgotPassword)
                .addGap(24, 24, 24)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegisterLink)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBranding, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
    new Dashboard().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnGuestActionPerformed

    private void lblRegisterLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterLinkMouseClicked
  RegisterFrame register = new RegisterFrame();
    register.setLocationRelativeTo(null); // biar muncul di tengah
    register.setVisible(true);
    }//GEN-LAST:event_lblRegisterLinkMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String email = txtEmail.getText().trim();
    String password = String.valueOf(jPasswordField1.getPassword());

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email tidak boleh kosong!");
        return;
    }

    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
        return;
    }

    UserDAO dao = new UserDAO();

    if (dao.login(email, password)) {

        JOptionPane.showMessageDialog(this, "Login berhasil!");

        Dashboard dashboard = new Dashboard();
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);

        dispose();

    } else {

        JOptionPane.showMessageDialog(this, "Email atau password salah!");

    }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    config.Koneksi.getConnection();

    java.awt.EventQueue.invokeLater(() -> {
        new LoginFrame().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jDashboardHeader;
    private javax.swing.JLabel jHerVoiceHeader;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFooterInfo;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblHerVoice;
    private javax.swing.JLabel lblNavSeparator;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegisterLink;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlBranding;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLoginForm;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JSeparator sepBranding;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
