/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author mulya
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelAdmin.class.getName());

    /**
     * Creates new form PanekAdmin
     */
    public PanelAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel25 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        pnlMenuBar = new javax.swing.JPanel();
        lblMenuFile = new javax.swing.JLabel();
        lblMenuPengguna = new javax.swing.JLabel();
        lblMenuKonten = new javax.swing.JLabel();
        lblMenuLaporan = new javax.swing.JLabel();
        lblMenuPengaturan = new javax.swing.JLabel();
        lblMenuBantuan = new javax.swing.JLabel();
        pnlActionBar = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        pnlAdminSidebar = new javax.swing.JPanel();
        pnlAdminPanel = new javax.swing.JPanel();
        lblAdminPanel = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlKelolaPengguna = new javax.swing.JPanel();
        lblKelolaPengguna = new javax.swing.JLabel();
        pnlLaporanMasuk = new javax.swing.JPanel();
        lblLaporanMasuk = new javax.swing.JLabel();
        pnlModerasiForum = new javax.swing.JPanel();
        lblModerasiForum = new javax.swing.JLabel();
        pnlVerifikasiKonselor = new javax.swing.JPanel();
        lblVerifikasiKonselor = new javax.swing.JLabel();
        pnlKelolaArtikel = new javax.swing.JPanel();
        lblKelolaArtikel = new javax.swing.JLabel();
        pnlPengaturan = new javax.swing.JPanel();
        lblPengaturan = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblCurrentPage = new javax.swing.JLabel();
        lblSeparatorFooter = new javax.swing.JLabel();
        lblLoginInfo = new javax.swing.JLabel();
        pnlMainContent = new javax.swing.JPanel();
        pnlDashboardContent = new javax.swing.JPanel();
        pnlStatTotalMember = new javax.swing.JPanel();
        lblStatTotalMemberTitle = new javax.swing.JLabel();
        lblStatTotalMemberValue = new javax.swing.JLabel();
        pnlStatLaporanBaru = new javax.swing.JPanel();
        lblStatLaporanBaruTitle = new javax.swing.JLabel();
        lblStatLaporanBaruValue = new javax.swing.JLabel();
        pnlStatMenungguVerifikasi = new javax.swing.JPanel();
        lblStatMenungguVerifikasiTitle = new javax.swing.JLabel();
        lblStatMenungguVerifikasiValue = new javax.swing.JLabel();
        pnlStatPostingan = new javax.swing.JPanel();
        lblStatPostinganTitle = new javax.swing.JLabel();
        lblStatPostinganValue = new javax.swing.JLabel();
        lblLaporanTerbaru = new javax.swing.JLabel();
        pnlLaporanTerbaru = new javax.swing.JPanel();
        lblHeaderID = new javax.swing.JLabel();
        lblHeaderJenis = new javax.swing.JLabel();
        lblHeaderTanggal = new javax.swing.JLabel();
        lblHeaderStatus = new javax.swing.JLabel();
        lblHeaderAksi = new javax.swing.JLabel();
        pnlLaporanRow1 = new javax.swing.JPanel();
        lblIdLaporan1 = new javax.swing.JLabel();
        lblJenisLaporan1 = new javax.swing.JLabel();
        lblTanggalLaporan1 = new javax.swing.JLabel();
        lblAksiLaporan1 = new javax.swing.JLabel();
        pnlLaporanRow2 = new javax.swing.JPanel();
        lblIdLaporan2 = new javax.swing.JLabel();
        lblJenisLaporan2 = new javax.swing.JLabel();
        lblTanggalLaporan2 = new javax.swing.JLabel();
        lblAksiLaporan2 = new javax.swing.JLabel();
        pnlStatusLaporanRow2 = new javax.swing.JPanel();
        lblStatusLaporan2 = new javax.swing.JLabel();
        pnlLaporanRow3 = new javax.swing.JPanel();
        lblIdLaporan3 = new javax.swing.JLabel();
        lblJenisLaporan3 = new javax.swing.JLabel();
        lblTanggalLaporan3 = new javax.swing.JLabel();
        pnlStatusLaporanRow3 = new javax.swing.JPanel();
        lblStatusLaporanRow3 = new javax.swing.JLabel();
        lblAksiLaporanRow3 = new javax.swing.JLabel();
        pnlLaporanRow4 = new javax.swing.JPanel();
        lblIdLaporan4 = new javax.swing.JLabel();
        lblJenisLaporan4 = new javax.swing.JLabel();
        lblTanggalLaporan4 = new javax.swing.JLabel();
        lblAksiLaporanRow4 = new javax.swing.JLabel();
        pnlStatusLaporanRow4 = new javax.swing.JPanel();
        lblStatusLaporanRow4 = new javax.swing.JLabel();
        pnlLaporanRow5 = new javax.swing.JPanel();
        lblIdLaporan5 = new javax.swing.JLabel();
        lblJenisLaporan5 = new javax.swing.JLabel();
        lblTanggalLaporan5 = new javax.swing.JLabel();
        pnlStatusLaporanRow5 = new javax.swing.JPanel();
        lblStatusLaporanRow5 = new javax.swing.JLabel();
        lblAksiLaporanRow5 = new javax.swing.JLabel();
        pnlStatusLaporanRow1 = new javax.swing.JPanel();
        lblStatusLaporanRow1 = new javax.swing.JLabel();

        jPanel25.setBackground(new java.awt.Color(224, 205, 213));

        jLabel41.setText("File");

        jLabel42.setText("Postingan");

        jLabel43.setText("Laporan");

        jLabel44.setText("Artikel");

        jLabel45.setText("Akun");

        jLabel46.setText("Bantuan");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel41)
                .addGap(44, 44, 44)
                .addComponent(jLabel42)
                .addGap(45, 45, 45)
                .addComponent(jLabel43)
                .addGap(50, 50, 50)
                .addComponent(jLabel44)
                .addGap(56, 56, 56)
                .addComponent(jLabel45)
                .addGap(57, 57, 57)
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(139, 61, 90));
        pnlMain.setPreferredSize(new java.awt.Dimension(700, 30));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Panel Admin");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(63, 63, 63)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlTopMenu.setBackground(new java.awt.Color(224, 205, 213));

        pnlMenuBar.setBackground(new java.awt.Color(224, 205, 213));

        lblMenuFile.setText("File");

        lblMenuPengguna.setText("Pengguna");

        lblMenuKonten.setText("Konten");

        lblMenuLaporan.setText("Laporan");

        lblMenuPengaturan.setText("Pengaturan");

        lblMenuBantuan.setText("Bantuan");

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMenuFile)
                .addGap(44, 44, 44)
                .addComponent(lblMenuPengguna)
                .addGap(45, 45, 45)
                .addComponent(lblMenuKonten)
                .addGap(50, 50, 50)
                .addComponent(lblMenuLaporan)
                .addGap(56, 56, 56)
                .addComponent(lblMenuPengaturan)
                .addGap(57, 57, 57)
                .addComponent(lblMenuBantuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuFile)
                    .addComponent(lblMenuPengguna)
                    .addComponent(lblMenuKonten)
                    .addComponent(lblMenuLaporan)
                    .addComponent(lblMenuPengaturan)
                    .addComponent(lblMenuBantuan))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTopMenuLayout = new javax.swing.GroupLayout(pnlTopMenu);
        pnlTopMenu.setLayout(pnlTopMenuLayout);
        pnlTopMenuLayout.setHorizontalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTopMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTopMenuLayout.setVerticalGroup(
            pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
            .addGroup(pnlTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTopMenuLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnRefresh.setText("Refresh");
        btnRefresh.setPreferredSize(new java.awt.Dimension(72, 20));

        btnExport.setText("Export");
        btnExport.setPreferredSize(new java.awt.Dimension(72, 20));

        javax.swing.GroupLayout pnlActionBarLayout = new javax.swing.GroupLayout(pnlActionBar);
        pnlActionBar.setLayout(pnlActionBarLayout);
        pnlActionBarLayout.setHorizontalGroup(
            pnlActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlActionBarLayout.setVerticalGroup(
            pnlActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActionBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlActionBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlAdminSidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminSidebar.setPreferredSize(new java.awt.Dimension(210, 407));

        pnlAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminPanel.setPreferredSize(new java.awt.Dimension(210, 407));

        lblAdminPanel.setForeground(new java.awt.Color(158, 123, 135));
        lblAdminPanel.setText("ADMIN PANEL");

        pnlDashboard.setBackground(new java.awt.Color(245, 224, 229));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKelolaPengguna.setBackground(new java.awt.Color(255, 255, 255));
        pnlKelolaPengguna.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKelolaPengguna.setForeground(new java.awt.Color(44, 26, 34));
        lblKelolaPengguna.setText("Kelola Pengguna");

        javax.swing.GroupLayout pnlKelolaPenggunaLayout = new javax.swing.GroupLayout(pnlKelolaPengguna);
        pnlKelolaPengguna.setLayout(pnlKelolaPenggunaLayout);
        pnlKelolaPenggunaLayout.setHorizontalGroup(
            pnlKelolaPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaPenggunaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKelolaPengguna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKelolaPenggunaLayout.setVerticalGroup(
            pnlKelolaPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKelolaPengguna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLaporanMasuk.setBackground(new java.awt.Color(255, 255, 255));
        pnlLaporanMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLaporanMasuk.setForeground(new java.awt.Color(44, 26, 34));
        lblLaporanMasuk.setText("Laporan Masuk");

        javax.swing.GroupLayout pnlLaporanMasukLayout = new javax.swing.GroupLayout(pnlLaporanMasuk);
        pnlLaporanMasuk.setLayout(pnlLaporanMasukLayout);
        pnlLaporanMasukLayout.setHorizontalGroup(
            pnlLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanMasukLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLaporanMasuk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLaporanMasukLayout.setVerticalGroup(
            pnlLaporanMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaporanMasuk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModerasiForum.setBackground(new java.awt.Color(255, 255, 255));
        pnlModerasiForum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblModerasiForum.setForeground(new java.awt.Color(44, 26, 34));
        lblModerasiForum.setText("Moderasi Forum");

        javax.swing.GroupLayout pnlModerasiForumLayout = new javax.swing.GroupLayout(pnlModerasiForum);
        pnlModerasiForum.setLayout(pnlModerasiForumLayout);
        pnlModerasiForumLayout.setHorizontalGroup(
            pnlModerasiForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModerasiForumLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblModerasiForum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModerasiForumLayout.setVerticalGroup(
            pnlModerasiForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModerasiForumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModerasiForum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVerifikasiKonselor.setBackground(new java.awt.Color(255, 255, 255));
        pnlVerifikasiKonselor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVerifikasiKonselor.setForeground(new java.awt.Color(44, 26, 34));
        lblVerifikasiKonselor.setText("Verifikasi Konselor");

        javax.swing.GroupLayout pnlVerifikasiKonselorLayout = new javax.swing.GroupLayout(pnlVerifikasiKonselor);
        pnlVerifikasiKonselor.setLayout(pnlVerifikasiKonselorLayout);
        pnlVerifikasiKonselorLayout.setHorizontalGroup(
            pnlVerifikasiKonselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifikasiKonselorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblVerifikasiKonselor)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlVerifikasiKonselorLayout.setVerticalGroup(
            pnlVerifikasiKonselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifikasiKonselorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVerifikasiKonselor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKelolaArtikel.setBackground(new java.awt.Color(255, 255, 255));
        pnlKelolaArtikel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKelolaArtikel.setForeground(new java.awt.Color(44, 26, 34));
        lblKelolaArtikel.setText("Kelola Artikel");

        javax.swing.GroupLayout pnlKelolaArtikelLayout = new javax.swing.GroupLayout(pnlKelolaArtikel);
        pnlKelolaArtikel.setLayout(pnlKelolaArtikelLayout);
        pnlKelolaArtikelLayout.setHorizontalGroup(
            pnlKelolaArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaArtikelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblKelolaArtikel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKelolaArtikelLayout.setVerticalGroup(
            pnlKelolaArtikelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKelolaArtikelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKelolaArtikel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPengaturan.setBackground(new java.awt.Color(255, 255, 255));
        pnlPengaturan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPengaturan.setForeground(new java.awt.Color(44, 26, 34));
        lblPengaturan.setText("Pengaturan");

        javax.swing.GroupLayout pnlPengaturanLayout = new javax.swing.GroupLayout(pnlPengaturan);
        pnlPengaturan.setLayout(pnlPengaturanLayout);
        pnlPengaturanLayout.setHorizontalGroup(
            pnlPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengaturanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblPengaturan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPengaturanLayout.setVerticalGroup(
            pnlPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengaturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPengaturan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminPanelLayout = new javax.swing.GroupLayout(pnlAdminPanel);
        pnlAdminPanel.setLayout(pnlAdminPanelLayout);
        pnlAdminPanelLayout.setHorizontalGroup(
            pnlAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAdminPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKelolaPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLaporanMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlModerasiForum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlVerifikasiKonselor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKelolaArtikel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdminPanelLayout.setVerticalGroup(
            pnlAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblAdminPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKelolaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlModerasiForum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlVerifikasiKonselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKelolaArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminSidebarLayout = new javax.swing.GroupLayout(pnlAdminSidebar);
        pnlAdminSidebar.setLayout(pnlAdminSidebarLayout);
        pnlAdminSidebarLayout.setHorizontalGroup(
            pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAdminSidebarLayout.createSequentialGroup()
                    .addComponent(pnlAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        pnlAdminSidebarLayout.setVerticalGroup(
            pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAdminSidebarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblCurrentPage.setText("Panel Admin");

        lblSeparatorFooter.setText("|");

        lblLoginInfo.setText("Login sebagai: Administrator");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparatorFooter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentPage)
                    .addComponent(lblSeparatorFooter)
                    .addComponent(lblLoginInfo))
                .addContainerGap())
        );

        pnlMainContent.setBackground(new java.awt.Color(251, 246, 240));

        pnlDashboardContent.setBackground(new java.awt.Color(251, 246, 240));

        pnlStatTotalMember.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatTotalMember.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatTotalMember.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatTotalMemberTitle.setText("Total Member");

        lblStatTotalMemberValue.setText("567");

        javax.swing.GroupLayout pnlStatTotalMemberLayout = new javax.swing.GroupLayout(pnlStatTotalMember);
        pnlStatTotalMember.setLayout(pnlStatTotalMemberLayout);
        pnlStatTotalMemberLayout.setHorizontalGroup(
            pnlStatTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatTotalMemberLayout.createSequentialGroup()
                .addGroup(pnlStatTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatTotalMemberLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStatTotalMemberTitle))
                    .addGroup(pnlStatTotalMemberLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblStatTotalMemberValue)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlStatTotalMemberLayout.setVerticalGroup(
            pnlStatTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatTotalMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatTotalMemberTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatTotalMemberValue)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlStatLaporanBaru.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatLaporanBaru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatLaporanBaru.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatLaporanBaruTitle.setText("Laporan Baru");

        lblStatLaporanBaruValue.setText("23");

        javax.swing.GroupLayout pnlStatLaporanBaruLayout = new javax.swing.GroupLayout(pnlStatLaporanBaru);
        pnlStatLaporanBaru.setLayout(pnlStatLaporanBaruLayout);
        pnlStatLaporanBaruLayout.setHorizontalGroup(
            pnlStatLaporanBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatLaporanBaruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatLaporanBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatLaporanBaruLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblStatLaporanBaruValue))
                    .addComponent(lblStatLaporanBaruTitle))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlStatLaporanBaruLayout.setVerticalGroup(
            pnlStatLaporanBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatLaporanBaruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatLaporanBaruTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatLaporanBaruValue)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlStatMenungguVerifikasi.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatMenungguVerifikasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatMenungguVerifikasi.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatMenungguVerifikasiTitle.setText("Menunggu Verif");

        lblStatMenungguVerifikasiValue.setText("3");

        javax.swing.GroupLayout pnlStatMenungguVerifikasiLayout = new javax.swing.GroupLayout(pnlStatMenungguVerifikasi);
        pnlStatMenungguVerifikasi.setLayout(pnlStatMenungguVerifikasiLayout);
        pnlStatMenungguVerifikasiLayout.setHorizontalGroup(
            pnlStatMenungguVerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatMenungguVerifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatMenungguVerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatMenungguVerifikasiLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblStatMenungguVerifikasiValue))
                    .addComponent(lblStatMenungguVerifikasiTitle))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlStatMenungguVerifikasiLayout.setVerticalGroup(
            pnlStatMenungguVerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatMenungguVerifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatMenungguVerifikasiTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatMenungguVerifikasiValue)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlStatPostingan.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatPostingan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStatPostingan.setPreferredSize(new java.awt.Dimension(110, 60));

        lblStatPostinganTitle.setText("Postingan Hari Ini");

        lblStatPostinganValue.setText("198");

        javax.swing.GroupLayout pnlStatPostinganLayout = new javax.swing.GroupLayout(pnlStatPostingan);
        pnlStatPostingan.setLayout(pnlStatPostinganLayout);
        pnlStatPostinganLayout.setHorizontalGroup(
            pnlStatPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatPostinganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatPostinganLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblStatPostinganValue))
                    .addComponent(lblStatPostinganTitle))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlStatPostinganLayout.setVerticalGroup(
            pnlStatPostinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatPostinganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatPostinganTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatPostinganValue)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblLaporanTerbaru.setText("Laporan Terbaru");

        pnlLaporanTerbaru.setBackground(new java.awt.Color(139, 61, 90));
        pnlLaporanTerbaru.setPreferredSize(new java.awt.Dimension(50, 100));

        lblHeaderID.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderID.setText("ID");

        lblHeaderJenis.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderJenis.setText("Jenis");

        lblHeaderTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTanggal.setText("Tanggal");

        lblHeaderStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderStatus.setText("Status");

        lblHeaderAksi.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderAksi.setText("Aksi");

        javax.swing.GroupLayout pnlLaporanTerbaruLayout = new javax.swing.GroupLayout(pnlLaporanTerbaru);
        pnlLaporanTerbaru.setLayout(pnlLaporanTerbaruLayout);
        pnlLaporanTerbaruLayout.setHorizontalGroup(
            pnlLaporanTerbaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanTerbaruLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblHeaderID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblHeaderJenis)
                .addGap(63, 63, 63)
                .addComponent(lblHeaderTanggal)
                .addGap(61, 61, 61)
                .addComponent(lblHeaderStatus)
                .addGap(59, 59, 59)
                .addComponent(lblHeaderAksi)
                .addGap(52, 52, 52))
        );
        pnlLaporanTerbaruLayout.setVerticalGroup(
            pnlLaporanTerbaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanTerbaruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaporanTerbaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeaderID)
                    .addComponent(lblHeaderJenis)
                    .addComponent(lblHeaderTanggal)
                    .addComponent(lblHeaderStatus)
                    .addComponent(lblHeaderAksi))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlLaporanRow1.setBackground(new java.awt.Color(251, 246, 240));
        pnlLaporanRow1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLaporanRow1.setPreferredSize(new java.awt.Dimension(488, 30));

        lblIdLaporan1.setText("#L001");

        lblJenisLaporan1.setText("KDRT");

        lblTanggalLaporan1.setText("8 Jun 2026");

        lblAksiLaporan1.setText("Tinjau");

        javax.swing.GroupLayout pnlLaporanRow1Layout = new javax.swing.GroupLayout(pnlLaporanRow1);
        pnlLaporanRow1.setLayout(pnlLaporanRow1Layout);
        pnlLaporanRow1Layout.setHorizontalGroup(
            pnlLaporanRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblIdLaporan1)
                .addGap(49, 49, 49)
                .addComponent(lblJenisLaporan1)
                .addGap(60, 60, 60)
                .addComponent(lblTanggalLaporan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(lblAksiLaporan1)
                .addGap(45, 45, 45))
        );
        pnlLaporanRow1Layout.setVerticalGroup(
            pnlLaporanRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLaporanRow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLaporanRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdLaporan1)
                    .addComponent(lblJenisLaporan1)
                    .addComponent(lblTanggalLaporan1)
                    .addComponent(lblAksiLaporan1))
                .addContainerGap())
        );

        pnlLaporanRow2.setBackground(new java.awt.Color(251, 246, 240));
        pnlLaporanRow2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLaporanRow2.setPreferredSize(new java.awt.Dimension(488, 30));

        lblIdLaporan2.setText("#L002");

        lblJenisLaporan2.setText("Pelecehan");

        lblTanggalLaporan2.setText("4 Jun 2026");

        lblAksiLaporan2.setText("Tinjau");

        pnlStatusLaporanRow2.setBackground(new java.awt.Color(255, 204, 153));

        lblStatusLaporan2.setText("Diproses");

        javax.swing.GroupLayout pnlStatusLaporanRow2Layout = new javax.swing.GroupLayout(pnlStatusLaporanRow2);
        pnlStatusLaporanRow2.setLayout(pnlStatusLaporanRow2Layout);
        pnlStatusLaporanRow2Layout.setHorizontalGroup(
            pnlStatusLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLaporanRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusLaporan2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatusLaporanRow2Layout.setVerticalGroup(
            pnlStatusLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLaporanRow2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatusLaporan2))
        );

        javax.swing.GroupLayout pnlLaporanRow2Layout = new javax.swing.GroupLayout(pnlLaporanRow2);
        pnlLaporanRow2.setLayout(pnlLaporanRow2Layout);
        pnlLaporanRow2Layout.setHorizontalGroup(
            pnlLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblIdLaporan2)
                .addGap(48, 48, 48)
                .addComponent(lblJenisLaporan2)
                .addGap(37, 37, 37)
                .addComponent(lblTanggalLaporan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(pnlStatusLaporanRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblAksiLaporan2)
                .addGap(45, 45, 45))
        );
        pnlLaporanRow2Layout.setVerticalGroup(
            pnlLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLaporanRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLaporanRow2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAksiLaporan2))
                    .addComponent(pnlStatusLaporanRow2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLaporanRow2Layout.createSequentialGroup()
                        .addGroup(pnlLaporanRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdLaporan2)
                            .addComponent(lblJenisLaporan2)
                            .addComponent(lblTanggalLaporan2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlLaporanRow3.setBackground(new java.awt.Color(251, 246, 240));
        pnlLaporanRow3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLaporanRow3.setPreferredSize(new java.awt.Dimension(488, 30));

        lblIdLaporan3.setText("#L003");

        lblJenisLaporan3.setText("Stalking");

        lblTanggalLaporan3.setText("31 Mei 2026");

        pnlStatusLaporanRow3.setBackground(new java.awt.Color(255, 204, 153));

        lblStatusLaporanRow3.setText("Diproses");

        javax.swing.GroupLayout pnlStatusLaporanRow3Layout = new javax.swing.GroupLayout(pnlStatusLaporanRow3);
        pnlStatusLaporanRow3.setLayout(pnlStatusLaporanRow3Layout);
        pnlStatusLaporanRow3Layout.setHorizontalGroup(
            pnlStatusLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLaporanRow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusLaporanRow3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatusLaporanRow3Layout.setVerticalGroup(
            pnlStatusLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLaporanRow3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatusLaporanRow3))
        );

        lblAksiLaporanRow3.setText("Tinjau");

        javax.swing.GroupLayout pnlLaporanRow3Layout = new javax.swing.GroupLayout(pnlLaporanRow3);
        pnlLaporanRow3.setLayout(pnlLaporanRow3Layout);
        pnlLaporanRow3Layout.setHorizontalGroup(
            pnlLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblIdLaporan3)
                .addGap(49, 49, 49)
                .addComponent(lblJenisLaporan3)
                .addGap(45, 45, 45)
                .addComponent(lblTanggalLaporan3)
                .addGap(34, 34, 34)
                .addComponent(pnlStatusLaporanRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblAksiLaporanRow3)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlLaporanRow3Layout.setVerticalGroup(
            pnlLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLaporanRow3Layout.createSequentialGroup()
                        .addGroup(pnlLaporanRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdLaporan3)
                            .addComponent(lblJenisLaporan3)
                            .addComponent(lblTanggalLaporan3))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addComponent(pnlStatusLaporanRow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLaporanRow3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAksiLaporanRow3)))
                .addGap(112, 112, 112))
        );

        pnlLaporanRow4.setBackground(new java.awt.Color(251, 246, 240));
        pnlLaporanRow4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLaporanRow4.setPreferredSize(new java.awt.Dimension(488, 30));

        lblIdLaporan4.setText("#L004");

        lblJenisLaporan4.setText("KDRT");

        lblTanggalLaporan4.setText("22 Mei 2026");

        lblAksiLaporanRow4.setText("Tinjau");

        pnlStatusLaporanRow4.setBackground(new java.awt.Color(204, 255, 204));

        lblStatusLaporanRow4.setText("Selesai");

        javax.swing.GroupLayout pnlStatusLaporanRow4Layout = new javax.swing.GroupLayout(pnlStatusLaporanRow4);
        pnlStatusLaporanRow4.setLayout(pnlStatusLaporanRow4Layout);
        pnlStatusLaporanRow4Layout.setHorizontalGroup(
            pnlStatusLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLaporanRow4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusLaporanRow4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatusLaporanRow4Layout.setVerticalGroup(
            pnlStatusLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLaporanRow4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatusLaporanRow4))
        );

        javax.swing.GroupLayout pnlLaporanRow4Layout = new javax.swing.GroupLayout(pnlLaporanRow4);
        pnlLaporanRow4.setLayout(pnlLaporanRow4Layout);
        pnlLaporanRow4Layout.setHorizontalGroup(
            pnlLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIdLaporan4)
                .addGap(47, 47, 47)
                .addComponent(lblJenisLaporan4)
                .addGap(57, 57, 57)
                .addComponent(lblTanggalLaporan4)
                .addGap(42, 42, 42)
                .addComponent(pnlStatusLaporanRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblAksiLaporanRow4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlLaporanRow4Layout.setVerticalGroup(
            pnlLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatusLaporanRow4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLaporanRow4Layout.createSequentialGroup()
                        .addGroup(pnlLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAksiLaporanRow4)
                            .addGroup(pnlLaporanRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIdLaporan4)
                                .addComponent(lblJenisLaporan4)
                                .addComponent(lblTanggalLaporan4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlLaporanRow5.setBackground(new java.awt.Color(251, 246, 240));
        pnlLaporanRow5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLaporanRow5.setPreferredSize(new java.awt.Dimension(488, 30));

        lblIdLaporan5.setText("#L005");

        lblJenisLaporan5.setText("Pelecehan");

        lblTanggalLaporan5.setText("27 Apr 2026");

        pnlStatusLaporanRow5.setBackground(new java.awt.Color(204, 255, 204));

        lblStatusLaporanRow5.setText("Selesai");

        javax.swing.GroupLayout pnlStatusLaporanRow5Layout = new javax.swing.GroupLayout(pnlStatusLaporanRow5);
        pnlStatusLaporanRow5.setLayout(pnlStatusLaporanRow5Layout);
        pnlStatusLaporanRow5Layout.setHorizontalGroup(
            pnlStatusLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLaporanRow5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusLaporanRow5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatusLaporanRow5Layout.setVerticalGroup(
            pnlStatusLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLaporanRow5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatusLaporanRow5))
        );

        lblAksiLaporanRow5.setText("Tinjau");

        javax.swing.GroupLayout pnlLaporanRow5Layout = new javax.swing.GroupLayout(pnlLaporanRow5);
        pnlLaporanRow5.setLayout(pnlLaporanRow5Layout);
        pnlLaporanRow5Layout.setHorizontalGroup(
            pnlLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblIdLaporan5)
                .addGap(47, 47, 47)
                .addComponent(lblJenisLaporan5)
                .addGap(35, 35, 35)
                .addComponent(lblTanggalLaporan5)
                .addGap(42, 42, 42)
                .addComponent(pnlStatusLaporanRow5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblAksiLaporanRow5)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlLaporanRow5Layout.setVerticalGroup(
            pnlLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanRow5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAksiLaporanRow5)
                    .addComponent(pnlStatusLaporanRow5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLaporanRow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdLaporan5)
                        .addComponent(lblJenisLaporan5)
                        .addComponent(lblTanggalLaporan5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDashboardContentLayout = new javax.swing.GroupLayout(pnlDashboardContent);
        pnlDashboardContent.setLayout(pnlDashboardContentLayout);
        pnlDashboardContentLayout.setHorizontalGroup(
            pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardContentLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                        .addComponent(pnlStatTotalMember, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatLaporanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatMenungguVerifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlStatPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLaporanTerbaru)
                    .addComponent(pnlLaporanTerbaru, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(pnlLaporanRow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLaporanRow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLaporanRow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLaporanRow4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLaporanRow5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlDashboardContentLayout.setVerticalGroup(
            pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStatPostingan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatMenungguVerifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatLaporanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatTotalMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLaporanTerbaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlLaporanTerbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLaporanRow5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pnlStatusLaporanRow1.setBackground(new java.awt.Color(255, 153, 153));

        lblStatusLaporanRow1.setText("Baru");

        javax.swing.GroupLayout pnlStatusLaporanRow1Layout = new javax.swing.GroupLayout(pnlStatusLaporanRow1);
        pnlStatusLaporanRow1.setLayout(pnlStatusLaporanRow1Layout);
        pnlStatusLaporanRow1Layout.setHorizontalGroup(
            pnlStatusLaporanRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLaporanRow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatusLaporanRow1)
                .addContainerGap())
        );
        pnlStatusLaporanRow1Layout.setVerticalGroup(
            pnlStatusLaporanRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLaporanRow1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatusLaporanRow1))
        );

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainContentLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(pnlStatusLaporanRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDashboardContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(pnlStatusLaporanRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDashboardContent, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addComponent(pnlTopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlActionBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAdminSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlActionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAdminSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(pnlMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblAksiLaporan1;
    private javax.swing.JLabel lblAksiLaporan2;
    private javax.swing.JLabel lblAksiLaporanRow3;
    private javax.swing.JLabel lblAksiLaporanRow4;
    private javax.swing.JLabel lblAksiLaporanRow5;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblCurrentPage;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblHeaderAksi;
    private javax.swing.JLabel lblHeaderID;
    private javax.swing.JLabel lblHeaderJenis;
    private javax.swing.JLabel lblHeaderStatus;
    private javax.swing.JLabel lblHeaderTanggal;
    private javax.swing.JLabel lblIdLaporan1;
    private javax.swing.JLabel lblIdLaporan2;
    private javax.swing.JLabel lblIdLaporan3;
    private javax.swing.JLabel lblIdLaporan4;
    private javax.swing.JLabel lblIdLaporan5;
    private javax.swing.JLabel lblJenisLaporan1;
    private javax.swing.JLabel lblJenisLaporan2;
    private javax.swing.JLabel lblJenisLaporan3;
    private javax.swing.JLabel lblJenisLaporan4;
    private javax.swing.JLabel lblJenisLaporan5;
    private javax.swing.JLabel lblKelolaArtikel;
    private javax.swing.JLabel lblKelolaPengguna;
    private javax.swing.JLabel lblLaporanMasuk;
    private javax.swing.JLabel lblLaporanTerbaru;
    private javax.swing.JLabel lblLoginInfo;
    private javax.swing.JLabel lblMenuBantuan;
    private javax.swing.JLabel lblMenuFile;
    private javax.swing.JLabel lblMenuKonten;
    private javax.swing.JLabel lblMenuLaporan;
    private javax.swing.JLabel lblMenuPengaturan;
    private javax.swing.JLabel lblMenuPengguna;
    private javax.swing.JLabel lblModerasiForum;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPengaturan;
    private javax.swing.JLabel lblSeparatorFooter;
    private javax.swing.JLabel lblStatLaporanBaruTitle;
    private javax.swing.JLabel lblStatLaporanBaruValue;
    private javax.swing.JLabel lblStatMenungguVerifikasiTitle;
    private javax.swing.JLabel lblStatMenungguVerifikasiValue;
    private javax.swing.JLabel lblStatPostinganTitle;
    private javax.swing.JLabel lblStatPostinganValue;
    private javax.swing.JLabel lblStatTotalMemberTitle;
    private javax.swing.JLabel lblStatTotalMemberValue;
    private javax.swing.JLabel lblStatusLaporan2;
    private javax.swing.JLabel lblStatusLaporanRow1;
    private javax.swing.JLabel lblStatusLaporanRow3;
    private javax.swing.JLabel lblStatusLaporanRow4;
    private javax.swing.JLabel lblStatusLaporanRow5;
    private javax.swing.JLabel lblTanggalLaporan1;
    private javax.swing.JLabel lblTanggalLaporan2;
    private javax.swing.JLabel lblTanggalLaporan3;
    private javax.swing.JLabel lblTanggalLaporan4;
    private javax.swing.JLabel lblTanggalLaporan5;
    private javax.swing.JLabel lblVerifikasiKonselor;
    private javax.swing.JPanel pnlActionBar;
    private javax.swing.JPanel pnlAdminPanel;
    private javax.swing.JPanel pnlAdminSidebar;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDashboardContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKelolaArtikel;
    private javax.swing.JPanel pnlKelolaPengguna;
    private javax.swing.JPanel pnlLaporanMasuk;
    private javax.swing.JPanel pnlLaporanRow1;
    private javax.swing.JPanel pnlLaporanRow2;
    private javax.swing.JPanel pnlLaporanRow3;
    private javax.swing.JPanel pnlLaporanRow4;
    private javax.swing.JPanel pnlLaporanRow5;
    private javax.swing.JPanel pnlLaporanTerbaru;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlModerasiForum;
    private javax.swing.JPanel pnlPengaturan;
    private javax.swing.JPanel pnlStatLaporanBaru;
    private javax.swing.JPanel pnlStatMenungguVerifikasi;
    private javax.swing.JPanel pnlStatPostingan;
    private javax.swing.JPanel pnlStatTotalMember;
    private javax.swing.JPanel pnlStatusLaporanRow1;
    private javax.swing.JPanel pnlStatusLaporanRow2;
    private javax.swing.JPanel pnlStatusLaporanRow3;
    private javax.swing.JPanel pnlStatusLaporanRow4;
    private javax.swing.JPanel pnlStatusLaporanRow5;
    private javax.swing.JPanel pnlTopMenu;
    private javax.swing.JPanel pnlVerifikasiKonselor;
    // End of variables declaration//GEN-END:variables
}
