/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nabil
 */
public class RegisterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lblSeparator = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblFooterInfo = new javax.swing.JLabel();
        pnlBranding = new javax.swing.JPanel();
        lblHerVoice = new javax.swing.JLabel();
        lblTagline = new javax.swing.JLabel();
        sepBranding = new javax.swing.JSeparator();
        lblDescription = new javax.swing.JLabel();
        pnlRegisterForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblDaftarSebagai = new javax.swing.JLabel();
        txtUlangiPassword = new javax.swing.JTextField();
        lblKonfirmasiPassword = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        chkAnonim = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();
        lblLoginLink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HerVoice - Register");
        setResizable(false);
        setSize(new java.awt.Dimension(400, 700));

        pnlMain.setBackground(new java.awt.Color(245, 240, 235));

        pnlHeader.setBackground(new java.awt.Color(139, 61, 90));

        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("Daftar Akun Baru");

        lblSeparator.setForeground(new java.awt.Color(255, 255, 255));
        lblSeparator.setText("|");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAppName)
                .addGap(14, 14, 14)
                .addComponent(lblSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppName)
                    .addComponent(lblPageTitle)
                    .addComponent(lblSeparator))
                .addContainerGap())
        );

        pnlFooter.setBackground(new java.awt.Color(230, 225, 225));
        pnlFooter.setMinimumSize(new java.awt.Dimension(0, 30));
        pnlFooter.setPreferredSize(new java.awt.Dimension(0, 30));

        lblFooterInfo.setText("Formulir Pendaftaran");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooterInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblFooterInfo)
                .addContainerGap())
        );

        pnlBranding.setBackground(new java.awt.Color(119, 47, 80));
        pnlBranding.setPreferredSize(new java.awt.Dimension(250, 400));

        lblHerVoice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHerVoice.setForeground(new java.awt.Color(255, 255, 255));
        lblHerVoice.setText("HerVoice");

        lblTagline.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(230, 210, 215));
        lblTagline.setText(" WHERE SILENCE FINDS ITS VOICE");

        sepBranding.setForeground(new java.awt.Color(170, 130, 140));
        sepBranding.setPreferredSize(new java.awt.Dimension(180, 10));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(210, 185, 190));
        lblDescription.setText("<html><center> Platform komunitas aman untuk perempuan<br> berbagi cerita dan mendapat dukungan. </center></html>");

        javax.swing.GroupLayout pnlBrandingLayout = new javax.swing.GroupLayout(pnlBranding);
        pnlBranding.setLayout(pnlBrandingLayout);
        pnlBrandingLayout.setHorizontalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblTagline)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblHerVoice)
                        .addGap(84, 84, 84))))
        );
        pnlBrandingLayout.setVerticalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lblHerVoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTagline)
                .addGap(12, 12, 12)
                .addComponent(sepBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRegisterForm.setBackground(new java.awt.Color(245, 240, 235));
        pnlRegisterForm.setPreferredSize(new java.awt.Dimension(250, 400));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(119, 47, 80));
        lblTitle.setText("Buat akun baru");

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(150, 120, 130));
        lblSubtitle.setText("Gratis, aman, dan terpercaya");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNama.setForeground(new java.awt.Color(90, 90, 90));
        lblNama.setText("Nama Lengkap");

        txtNama.setText("Masukkan nama lengkap");
        txtNama.addActionListener(this::txtNamaActionPerformed);

        txtEmail.setText("contoh@email.com");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(90, 90, 90));
        lblEmail.setText("Alamat Email");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(90, 90, 90));
        lblPassword.setText("Password");

        txtPassword.setText("Min. 8 karakter");
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        lblDaftarSebagai.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDaftarSebagai.setForeground(new java.awt.Color(90, 90, 90));
        lblDaftarSebagai.setText("Daftar sebagai");

        txtUlangiPassword.setText("Ulangi password");
        txtUlangiPassword.addActionListener(this::txtUlangiPasswordActionPerformed);

        lblKonfirmasiPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblKonfirmasiPassword.setForeground(new java.awt.Color(90, 90, 90));
        lblKonfirmasiPassword.setText("Konfirmasi Password");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member (Pengguna Umum)" }));
        cmbRole.addActionListener(this::cmbRoleActionPerformed);

        chkAnonim.setForeground(new java.awt.Color(119, 47, 80));
        chkAnonim.setSelected(true);
        chkAnonim.setText("Aktifkan mode anonim (identitas disembunyikan)");

        btnRegister.setBackground(new java.awt.Color(119, 47, 80));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Daftar Sekarang");

        lblLoginLink.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblLoginLink.setForeground(new java.awt.Color(150, 120, 130));
        lblLoginLink.setText("Sudah punya akun? Masuk di sini");

        javax.swing.GroupLayout pnlRegisterFormLayout = new javax.swing.GroupLayout(pnlRegisterForm);
        pnlRegisterForm.setLayout(pnlRegisterFormLayout);
        pnlRegisterFormLayout.setHorizontalGroup(
            pnlRegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                .addGroup(pnlRegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSubtitle))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNama))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmail))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPassword))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDaftarSebagai))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKonfirmasiPassword))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUlangiPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoginLink, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAnonim)))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnRegister))
                    .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pnlRegisterFormLayout.setVerticalGroup(
            pnlRegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKonfirmasiPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUlangiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDaftarSebagai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAnonim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginLink)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlBranding, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRegisterForm, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBranding, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUlangiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUlangiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUlangiPasswordActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chkAnonim;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblDaftarSebagai;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFooterInfo;
    private javax.swing.JLabel lblHerVoice;
    private javax.swing.JLabel lblKonfirmasiPassword;
    private javax.swing.JLabel lblLoginLink;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBranding;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRegisterForm;
    private javax.swing.JSeparator sepBranding;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUlangiPassword;
    // End of variables declaration//GEN-END:variables
}
