/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author mulya
 */
public class SplashScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SplashScreen.class.getName());

    /**
     * Creates new form SplashScreen
     */
public SplashScreen() {
    initComponents();

    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                for (int i = 0; i <= 100; i++) {
                    pbLoading.setValue(i);
                    Thread.sleep(30);
                }

                LoginFrame login = new LoginFrame();
                login.setVisible(true);
                dispose();

            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
    }).start();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlBranding = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pbLoading = new javax.swing.JProgressBar();
        lblTagline = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        pnlMain.setBackground(new java.awt.Color(245, 240, 235));
        pnlMain.setPreferredSize(new java.awt.Dimension(700, 500));

        pnlBranding.setBackground(new java.awt.Color(119, 47, 80));
        pnlBranding.setPreferredSize(new java.awt.Dimension(250, 400));

        lblAppName.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("HerVoice");

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(240, 220, 230));
        lblLogo.setText("Ruang Aman untuk Bersuara");

        pbLoading.setBorderPainted(false);

        lblTagline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(220, 180, 200));
        lblTagline.setText("Memuat aplikasi...");

        lblLoading.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(200, 160, 180));
        lblLoading.setText("v1.0.0");

        javax.swing.GroupLayout pnlBrandingLayout = new javax.swing.GroupLayout(pnlBranding);
        pnlBranding.setLayout(pnlBrandingLayout);
        pnlBrandingLayout.setHorizontalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblTagline)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrandingLayout.createSequentialGroup()
                        .addComponent(lblLoading)
                        .addGap(334, 334, 334))))
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGroup(pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBrandingLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblLogo))
                    .addGroup(pnlBrandingLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(pbLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBrandingLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(lblAppName)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        pnlBrandingLayout.setVerticalGroup(
            pnlBrandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrandingLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lblAppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo)
                .addGap(12, 12, 12)
                .addComponent(pbLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTagline)
                .addGap(18, 18, 18)
                .addComponent(lblLoading)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlBranding, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBranding, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    config.Koneksi.getConnection();
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            new SplashScreen().setVisible(true);
        }
    });

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JProgressBar pbLoading;
    private javax.swing.JPanel pnlBranding;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
